# Generated by Django 5.2.8 on 2025-12-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='client_phone',
            field=models.CharField(blank=True, help_text='Numéro Mobile Money du client', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='webhook_data',
            field=models.JSONField(blank=True, default=dict, help_text='Données brutes du webhook'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('airtel_money', 'Airtel Money'), ('moov_money', 'Moov Money'), ('card', 'Carte Bancaire'), ('cash', 'Espèces')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('success', 'Succès'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
