# Generated by Django 5.2.8 on 2025-12-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_client_name_payment_client_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fees_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Frais de transaction inclus', max_digits=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Montant total payé', max_digits=10),
        ),
    ]
