# Generated by Django 5.2.8 on 2025-12-06 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_city_order_payment_fees'),
        ('payments', '0003_payment_fees_amount_alter_payment_amount'),
        ('products', '0002_product_is_sponsored_product_sponsor_expiry_and_more'),
        ('stores', '0005_add_default_store_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_type', models.CharField(default='promotion', help_text='Type: promotion, referral, loyalty, compensation, etc.', max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('used', 'Utilisé'), ('expired', 'Expiré')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crédit Client',
                'verbose_name_plural': 'Crédits Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee_from_client', models.DecimalField(decimal_places=2, help_text='Frais payés par le client', max_digits=10)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('calculated_payout', models.DecimalField(decimal_places=2, help_text='Montant calculé pour le livreur', max_digits=10)),
                ('platform_profit', models.DecimalField(decimal_places=2, default=0.0, help_text='Bénéfice de la plateforme', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Payé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_agent', models.ForeignKey(limit_choices_to={'user_type': 'delivery_agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_payout', to='orders.order')),
            ],
            options={
                'verbose_name': 'Paiement Livreur',
                'verbose_name_plural': 'Paiements Livreurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsoredProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_type', models.CharField(default='featured', help_text='Type: featured, banner, top_search, etc.', max_length=50)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('paused', 'Suspendu')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_products', to='stores.store')),
            ],
            options={
                'verbose_name': 'Produit Sponsorisé',
                'verbose_name_plural': 'Produits Sponsorisés',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='StoreSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Mode Pro', max_length=100)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('cancelled', 'Annulé'), ('expired', 'Expiré'), ('pending_payment', 'Attente paiement')], default='active', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='stores.store')),
            ],
            options={
                'verbose_name': 'Abonnement Magasin',
                'verbose_name_plural': 'Abonnements Magasins',
                'ordering': ['-end_date'],
            },
        ),
    ]
