# Generated by Django 5.2.9 on 2025-12-08 18:20

import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_city_order_payment_fees'),
        ('payments', '0004_clientcredit_deliverypayout_sponsoredproduct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=payments.models.gen_ref, max_length=64, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('provider', models.CharField(default='cinetpay', max_length=32)),
                ('status', models.CharField(default='WAITING', max_length=32)),
                ('payment_token', models.CharField(blank=True, max_length=512, null=True)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intent de Paiement',
                'verbose_name_plural': 'Intents de Paiement',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_tx_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(max_length=32)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentintent')),
            ],
            options={
                'verbose_name': 'Transaction de Paiement',
                'verbose_name_plural': 'Transactions de Paiement',
            },
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['reference'], name='payments_pa_referen_544edd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status'], name='payments_pa_status_f8bf5e_idx'),
        ),
    ]
