# Generated by Django 5.2 on 2025-12-08 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentintent_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('plan_type', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix mensuel en FCFA', max_digits=10)),
                ('max_products', models.IntegerField(blank=True, help_text='Limite de produits (null = illimité)', null=True)),
                ('can_sponsor_products', models.BooleanField(default=False, help_text='Peut sponsoriser des produits')),
                ('has_statistics', models.BooleanField(default=False, help_text='Accès aux statistiques avancées')),
                ('has_custom_page', models.BooleanField(default=False, help_text='Page personnalisée')),
                ('has_priority_support', models.BooleanField(default=False, help_text='Support VIP')),
                ('priority_listing', models.IntegerField(default=0, help_text='Ordre de priorité dans les listings (plus élevé = plus visible)')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Taux de commission spécifique au plan (si null, utilise le taux par défaut)', max_digits=5, null=True)),
                ('description', models.TextField(blank=True)),
                ('features_json', models.JSONField(blank=True, default=list, help_text='Liste des fonctionnalités en JSON')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['price'],
            },
        ),
        migrations.AlterField(
            model_name='storesubscription',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='storesubscription',
            name='plan_name',
            field=models.CharField(default='Starter', max_length=100),
        ),
        migrations.AddField(
            model_name='storesubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.subscriptionplan'),
        ),
    ]
