# Generated by Django 5.2.8 on 2025-12-09 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_city_order_payment_fees'),
        ('payments', '0006_add_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_priority_orders', models.IntegerField(default=0, help_text='Nombre de commandes prioritaires par mois')),
                ('discount_rate', models.FloatField(default=0, help_text='Réduction en % sur les frais de livraison')),
                ('can_schedule_delivery', models.BooleanField(default=False, help_text='Peut planifier une livraison')),
                ('can_track_realtime', models.BooleanField(default=False, help_text='Peut suivre en temps réel')),
                ('can_contact_driver', models.BooleanField(default=False, help_text='Peut contacter le livreur')),
                ('priority_support', models.BooleanField(default=False, help_text='Support prioritaire')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forfait Client',
                'verbose_name_plural': 'Forfaits Clients',
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='ClientForfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(help_text="Date d'expiration du forfait")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé')], default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=True, help_text='Renouvellement automatique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_forfait', to=settings.AUTH_USER_MODEL)),
                ('forfait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='payments.forfait')),
            ],
            options={
                'verbose_name': 'Forfait Client',
                'verbose_name_plural': 'Forfaits Clients',
                'ordering': ['-expiration_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCallbackLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField(default=200, help_text='Code de réponse HTTP')),
                ('raw_data', models.JSONField(help_text='Données brutes du webhook')),
                ('signature_valid', models.BooleanField(default=False, help_text='Signature Flutterwave validée')),
                ('processed', models.BooleanField(default=False, help_text='Webhook traité avec succès')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'Log Callback Flutterwave',
                'verbose_name_plural': 'Logs Callbacks Flutterwave',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payout_type', models.CharField(choices=[('delivery', 'Paiement Livreur'), ('merchant', 'Paiement Commerçant'), ('refund', 'Remboursement')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant en FCFA', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('paid', 'Payé'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('flutterwave_payout_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('reason', models.TextField(blank=True, help_text='Raison du paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Quand le paiement a été effectué', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_payouts', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement (Payout)',
                'verbose_name_plural': 'Paiements (Payouts)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_pa_user_id_024e9b_idx'), models.Index(fields=['payout_type', 'status'], name='payments_pa_payout__6becde_idx')],
            },
        ),
    ]
