# Generated by Django 5.2.9 on 2025-12-25 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_add_forfait_payout_models'),
        ('stores', '0008_add_offers_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='commission_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicateur appliqué au taux de commission de base (ex: 0.60 pour -40%)', max_digits=4),
        ),
        migrations.CreateModel(
            name='CategoryCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.DecimalField(decimal_places=2, default=8.0, help_text='Taux de commission de base en %', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_commission', to='stores.storecategory')),
            ],
            options={
                'verbose_name': 'Commission Par Catégorie',
                'verbose_name_plural': 'Commissions Par Catégorie',
                'ordering': ['store_category'],
            },
        ),
    ]
