# Generated by Django 5.2.9 on 2025-12-25 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_subscriptionplan_commission_multiplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCommissionChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='payments.categorycommission')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique Commission Catégorie',
                'verbose_name_plural': 'Historique Commissions Catégorie',
                'ordering': ['-created_at'],
            },
        ),
    ]
