# Generated by Django 5.2 on 2026-01-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_categorycommissionchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_access_b2b',
            field=models.BooleanField(default=False, help_text='Accès approvisionnement B2B (pour stores B2C)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_b2b_visibility',
            field=models.BooleanField(default=False, help_text='Visibilité maximale dans catalogue B2B (pour grossistes)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_orders_per_month',
            field=models.IntegerField(blank=True, help_text='Limite commandes/mois (null = illimité)', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('business', 'Business')], max_length=20, unique=True),
        ),
    ]
