# Generated by Django 5.2 on 2026-01-04 18:09

from django.db import migrations, models
from decimal import Decimal


def migrate_commission_multiplier_to_percent(apps, schema_editor):
    """
    Convertit commission_multiplier en commission_reduction_percent
    Ex: multiplier 0.60 → reduction_percent 40 (car 1 - 0.60 = 0.40 = 40%)
    """
    SubscriptionPlan = apps.get_model('payments', 'SubscriptionPlan')
    
    for plan in SubscriptionPlan.objects.all():
        if hasattr(plan, 'commission_multiplier') and plan.commission_multiplier is not None:
            # Formule: reduction_percent = (1 - multiplier) * 100
            multiplier = Decimal(str(plan.commission_multiplier))
            reduction_percent = int((Decimal('1') - multiplier) * Decimal('100'))
            plan.commission_reduction_percent = max(0, min(100, reduction_percent))  # Limiter entre 0 et 100
            plan.save(update_fields=['commission_reduction_percent'])
            print(f"[MIGRATION] {plan.name}: multiplier {multiplier} -> reduction {reduction_percent}%")


def reverse_migration(apps, schema_editor):
    """
    Restaure commission_multiplier depuis commission_reduction_percent
    """
    SubscriptionPlan = apps.get_model('payments', 'SubscriptionPlan')
    
    for plan in SubscriptionPlan.objects.all():
        if hasattr(plan, 'commission_reduction_percent') and plan.commission_reduction_percent is not None:
            # Formule inverse: multiplier = 1 - (reduction_percent / 100)
            reduction_percent = Decimal(str(plan.commission_reduction_percent))
            multiplier = Decimal('1') - (reduction_percent / Decimal('100'))
            plan.commission_multiplier = multiplier
            plan.save(update_fields=['commission_multiplier'])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_subscriptionplan_can_access_b2b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_export_financial_reports',
            field=models.BooleanField(default=False, help_text='Peut exporter les rapports financiers (Excel/PDF)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_offer_express_delivery',
            field=models.BooleanField(default=False, help_text='Autorise la livraison express (option payante pour le client)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_sell_non_food_products',
            field=models.BooleanField(default=True, help_text='Autorise la vente de produits non alimentaires'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='commission_reduction_percent',
            field=models.IntegerField(default=0, help_text='Réduction de commission en % par rapport au taux de base (0-100). Ex: 40 = -40%, 75 = -75%'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_advanced_delivery_tracking',
            field=models.BooleanField(default=False, help_text='Accès au suivi détaillé des livraisons (GPS, notifications en temps réel)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_products_non_food',
            field=models.IntegerField(blank=True, help_text='Limite de produits non alimentaires (null = illimité si can_sell_non_food_products=True)', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='service_fee_client_amount',
            field=models.IntegerField(default=500, help_text='Montant des frais de service payés par le client final par commande B2C (FCFA)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='service_fee_to_wholesaler_amount',
            field=models.IntegerField(default=1000, help_text='Frais facturés au commerce B2C pour chaque commande B2B vers un grossiste (FCFA)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='support_level',
            field=models.CharField(choices=[('standard', 'Standard'), ('prioritaire', 'Prioritaire'), ('dedie', 'Dédié VIP')], default='standard', help_text='Niveau de support client', max_length=20),
        ),
        # Migrer les données de commission_multiplier vers commission_reduction_percent
        migrations.RunPython(migrate_commission_multiplier_to_percent, reverse_migration),
    ]
