# Generated by Django 5.2 on 2026-01-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_enhance_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='can_export_financial_reports',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_export_excel',
            field=models.BooleanField(default=False, help_text='Peut exporter les rapports en Excel/CSV'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_export_pdf',
            field=models.BooleanField(default=False, help_text='Peut exporter les rapports en PDF officiel'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_view_basic_reports',
            field=models.BooleanField(default=True, help_text='Peut voir les rapports basiques (ventes du jour/mois, commissions)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_view_detailed_reports',
            field=models.BooleanField(default=False, help_text='Peut voir les détails par commande et par catégorie'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='history_limit_days',
            field=models.IntegerField(blank=True, help_text="Limite d'historique en jours (null = illimité)", null=True),
        ),
    ]
