# Generated by Django 5.2 on 2026-01-04 20:20

from django.db import migrations, models


def migrate_has_statistics_to_detailed_reports(apps, schema_editor):
    """Migre has_statistics=True vers can_view_detailed_reports=True"""
    SubscriptionPlan = apps.get_model('payments', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(has_statistics=True).update(can_view_detailed_reports=True)


def reverse_migrate(apps, schema_editor):
    """Reverse: migre can_view_detailed_reports vers has_statistics"""
    SubscriptionPlan = apps.get_model('payments', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(can_view_detailed_reports=True).update(has_statistics=True)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_refine_reports_and_exports'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='applies_to',
            field=models.CharField(choices=[('b2c', 'B2C Store uniquement'), ('b2b_buyer', 'B2B Buyer (boutique cliente)'), ('b2b_wholesaler', 'B2B Grossiste'), ('both', 'B2C et B2B')], default='b2c', help_text="Type de magasin auquel ce plan s'applique", max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='b2b_catalog_priority',
            field=models.IntegerField(default=0, help_text="Priorité d'affichage dans le catalogue B2B (plus élevé = plus visible)"),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='b2b_featured_access',
            field=models.BooleanField(default=False, help_text='Accès prioritaire aux grossistes mis en avant'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_export_finance_csv',
            field=models.BooleanField(default=False, help_text='Peut exporter les rapports financiers B2B en Excel/CSV'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_export_finance_pdf',
            field=models.BooleanField(default=False, help_text='Peut exporter les rapports financiers B2B en PDF officiel'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_view_finance_basic',
            field=models.BooleanField(default=True, help_text='Peut voir les rapports financiers basiques (ventes B2B du jour/mois)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_view_finance_detailed',
            field=models.BooleanField(default=False, help_text='Peut voir les détails financiers par commande B2B et par catégorie'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='finance_history_limit_days',
            field=models.IntegerField(blank=True, help_text="Limite d'historique financier B2B en jours (null = illimité)", null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_b2b_monthly_orders',
            field=models.IntegerField(blank=True, help_text='Nombre max de commandes B2B par mois (null = illimité)', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_b2b_suppliers',
            field=models.IntegerField(blank=True, help_text='Nombre max de grossistes avec lesquels commander (null = illimité)', null=True),
        ),
        migrations.RunPython(
            migrate_has_statistics_to_detailed_reports,
            reverse_migrate,
        ),
    ]
