# Generated by Django 6.0.3 on 2026-03-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_enhance_subscription_plan_b2b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='service_fee_client_amount',
            field=models.IntegerField(default=0, help_text='Montant desactive (laisser a 0)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='service_fee_to_wholesaler_amount',
            field=models.IntegerField(default=0, help_text='Montant desactive (laisser a 0)'),
        ),
    ]
