import decimal
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('payments', '0014_alter_subscriptionplan_service_fee_client_amount_and_more'), ('orders', '0008_alter_order_delivery_cost_alter_order_delivery_fee_and_more'), ('stores', '0013_store_payment_preferences'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='PaymentArrangement', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('flow', models.CharField(choices=[('direct_split', 'Produits au commerce, livraison au livreur'), ('store_collects_all', 'Tout au commerce, qui règle le livreur'), ('courier_cash', 'Espèces collectées par le livreur'), ('platform_online', 'Paiement en ligne à Gaboshop')], max_length=30)), ('method', models.CharField(max_length=30)), ('delivery_method', models.CharField(blank=True, max_length=30)), ('policy_snapshot', models.JSONField(default=dict)), ('products_amount', models.DecimalField(decimal_places=2, max_digits=14)), ('delivery_amount', models.DecimalField(decimal_places=2, max_digits=14)), ('commission_rate', models.DecimalField(decimal_places=4, default=decimal.Decimal('0'), max_digits=7)), ('commission_amount', models.DecimalField(decimal_places=2, max_digits=14)), ('created_at', models.DateTimeField(auto_now_add=True)), ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)), ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_arrangement', to='orders.order')), ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_arrangements', to='stores.store'))], options={'ordering': ['-created_at']}),
        migrations.CreateModel(name='PaymentObligation', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('kind', models.CharField(choices=[('products', 'Règlement du client'), ('delivery', 'Rémunération du livreur'), ('courier_remittance', 'Reversement des espèces au commerce'), ('commission', 'Commission Gaboshop'), ('failed_trip', 'Indemnité course échouée')], max_length=30)), ('payer', models.CharField(choices=[('client', 'Client'), ('store', 'Commerce'), ('courier', 'Livreur'), ('platform', 'Gaboshop')], max_length=15)), ('payee', models.CharField(choices=[('client', 'Client'), ('store', 'Commerce'), ('courier', 'Livreur'), ('platform', 'Gaboshop')], max_length=15)), ('amount', models.DecimalField(decimal_places=2, max_digits=14)), ('status', models.CharField(choices=[('not_due', 'Non exigible'), ('unpaid', 'Impayé'), ('pending', 'En attente'), ('partially_paid', 'Partiellement payé'), ('paid', 'Payé'), ('overdue', 'En retard'), ('waived', 'Exonéré'), ('cancelled', 'Annulé'), ('partially_refunded', 'Partiellement remboursé'), ('refunded', 'Remboursé')], db_index=True, default='unpaid', max_length=30)), ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)), ('requires_delivery_proof', models.BooleanField(default=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='payments.paymentarrangement'))], options={'ordering': ['id']}),
        migrations.CreateModel(name='CommissionSettlement', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('receipt_number', models.CharField(editable=False, max_length=40, unique=True)), ('amount', models.DecimalField(decimal_places=2, max_digits=14)), ('method', models.CharField(max_length=30)), ('reference', models.CharField(blank=True, max_length=150)), ('comment', models.TextField(blank=True)), ('proof', models.FileField(blank=True, null=True, upload_to='payments/settlement_proofs/')), ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_confirmation', 'À confirmer'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='pending_confirmation', max_length=30)), ('paid_at', models.DateTimeField(default=django.utils.timezone.now)), ('confirmed_at', models.DateTimeField(blank=True, null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collected_settlements', to=settings.AUTH_USER_MODEL)), ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_settlements', to=settings.AUTH_USER_MODEL)), ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_settlements', to='stores.store'))]),
        migrations.CreateModel(name='PaymentReceipt', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('amount', models.DecimalField(decimal_places=2, max_digits=14)), ('method', models.CharField(max_length=30)), ('reference', models.CharField(max_length=150)), ('receipt_number', models.CharField(editable=False, max_length=40, unique=True)), ('proof', models.FileField(blank=True, null=True, upload_to='payments/receipt_proofs/')), ('comment', models.TextField(blank=True)), ('status', models.CharField(choices=[('pending', 'À confirmer'), ('confirmed', 'Confirmé'), ('rejected', 'Rejeté')], default='pending', max_length=20)), ('confirmed_at', models.DateTimeField(blank=True, null=True)), ('idempotency_key', models.CharField(max_length=100, unique=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)), ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)), ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='payments.paymentobligation'))], options={'ordering': ['created_at', 'id']}),
        migrations.CreateModel(name='PaymentAdjustment', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('adjustment_type', models.CharField(choices=[('refund', 'Remboursement'), ('commission_credit', 'Avoir commission'), ('correction', 'Correction')], default='refund', max_length=30)), ('status', models.CharField(choices=[('pending', 'À confirmer'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='confirmed', max_length=20)), ('amount', models.DecimalField(decimal_places=2, max_digits=14)), ('reason', models.TextField()), ('reference', models.CharField(max_length=150)), ('idempotency_key', models.CharField(max_length=100, unique=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)), ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='payments.paymentobligation'))], options={'ordering': ['created_at', 'id']}),
        migrations.CreateModel(name='SettlementAllocation', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('amount', models.DecimalField(decimal_places=2, max_digits=14)), ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_allocations', to='payments.paymentobligation')), ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.commissionsettlement'))]),
        migrations.AddConstraint(model_name='paymentarrangement', constraint=models.CheckConstraint(condition=models.Q(('products_amount__gte', 0)), name='direct_products_nonnegative')),
        migrations.AddConstraint(model_name='paymentarrangement', constraint=models.CheckConstraint(condition=models.Q(('delivery_amount__gte', 0)), name='direct_delivery_nonnegative')),
        migrations.AddConstraint(model_name='paymentarrangement', constraint=models.CheckConstraint(condition=models.Q(('commission_amount__gte', 0)), name='direct_commission_nonnegative')),
        migrations.AddConstraint(model_name='paymentobligation', constraint=models.UniqueConstraint(fields=('arrangement', 'kind'), name='direct_unique_obligation_kind')),
        migrations.AddConstraint(model_name='paymentobligation', constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='direct_obligation_nonnegative')),
        migrations.AddConstraint(model_name='paymentreceipt', constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='direct_receipt_positive')),
        migrations.AddConstraint(model_name='paymentreceipt', constraint=models.UniqueConstraint(fields=('obligation', 'reference'), name='direct_unique_receipt_reference')),
        migrations.AddConstraint(model_name='paymentadjustment', constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='direct_adjustment_positive')),
        migrations.AddConstraint(model_name='paymentadjustment', constraint=models.UniqueConstraint(fields=('obligation', 'reference'), name='direct_unique_refund_reference')),
        migrations.AddConstraint(model_name='settlementallocation', constraint=models.UniqueConstraint(fields=('settlement', 'obligation'), name='unique_settlement_obligation')),
        migrations.AddConstraint(model_name='settlementallocation', constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='settlement_allocation_positive')),
    ]
