# Generated by Django 5.2 on 2026-10-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_receipt_rejection_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentobligation',
            name='kind',
            field=models.CharField(choices=[('products', 'Règlement du client'), ('delivery', 'Rémunération du livreur'), ('delivery_collection', 'Encaissement des frais de livraison'), ('courier_remittance', 'Reversement des espèces au commerce'), ('commission', 'Commission Gaboshop'), ('failed_trip', 'Indemnité course échouée')], max_length=30),
        ),
    ]
