# Generated by Django 6.0.8 on 2026-10-04 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_align_order_model_state'),
        ('payments', '0017_distinguish_delivery_collection'),
        ('stores', '0014_store_agent_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('products_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('includes_delivery', models.BooleanField(default=False, help_text='Le commerce gère sa livraison: part livraison incluse')),
                ('agent_code', models.CharField(blank=True, default='', help_text='Code agent du commerce au moment du versement', max_length=100)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('paid', 'Payé'), ('failed', 'Échec'), ('skipped', 'Sans objet')], db_index=True, default='pending', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='store_payout', to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_payouts', to='stores.store')),
            ],
            options={
                'verbose_name': 'Versement commerce',
                'verbose_name_plural': 'Versements commerces',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='store_payout_amount_nonnegative')],
            },
        ),
    ]
