# Generated by Django 5.2.17 on 2026-10-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0018_store_payout"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypayout",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Pourquoi le versement attend ou a échoué",
                max_length=255,
            ),
        ),
    ]
