# Generated by Django 6.0.9 on 2026-10-10 20:53

from django.db import migrations, models


# Valeurs de départ, modifiables ensuite dans la console admin (Forfaits).
STARTING_FOOD_LIMITS = {'free': 10, 'pro': 50}


def set_starting_food_limits(apps, schema_editor):
    SubscriptionPlan = apps.get_model('payments', 'SubscriptionPlan')
    for plan_type, limit in STARTING_FOOD_LIMITS.items():
        SubscriptionPlan.objects.filter(plan_type=plan_type, max_products_food__isnull=True).update(
            max_products_food=limit
        )


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0019_deliverypayout_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_products_food",
            field=models.IntegerField(
                blank=True,
                help_text="Limite de produits alimentaires (null = illimité). Le non alimentaire n'est limité que par max_products.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="can_sell_non_food_products",
            field=models.BooleanField(
                default=True, help_text="Ancien réglage, plus appliqué"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_products_non_food",
            field=models.IntegerField(
                blank=True, help_text="Ancien réglage, plus appliqué", null=True
            ),
        ),
        migrations.RunPython(set_starting_food_limits, migrations.RunPython.noop),
    ]
