# Generated by Django 5.2.8 on 2025-11-26 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('assigned', 'Assignée'), ('picked_up', 'Colis récupéré'), ('in_transit', 'En cours'), ('delivered', 'Livrée'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('pickup_address', models.TextField(help_text='Adresse du magasin')),
                ('delivery_address', models.TextField(help_text='Adresse du client')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('agent_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True, help_text='Notes du livreur')),
                ('customer_feedback', models.TextField(blank=True, help_text='Retour client')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Note 1-5', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_agent', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'delivery_agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='delivery.delivery')),
            ],
            options={
                'verbose_name': 'Suivi de Livraison',
                'verbose_name_plural': 'Suivis de Livraison',
                'ordering': ['-created_at'],
            },
        ),
    ]
