# Generated by Django 5.2.8 on 2025-12-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='code_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_code',
            field=models.CharField(blank=True, help_text='Code PIN à 4-6 chiffres', max_length=6),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_proofs/'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_proof_type',
            field=models.CharField(blank=True, choices=[('photo', 'Photo de livraison'), ('signature', 'Signature client'), ('pin', 'Code PIN')], max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='distance_to_store',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance en km', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Durée estimée en minutes', null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_auto_assigned',
            field=models.BooleanField(default=False, help_text='Assigné automatiquement'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('waiting', "En attente d'assignation"), ('pending', "En attente d'acceptation"), ('assigned', 'Assignée'), ('accepted', 'Acceptée par livreur'), ('picked_up', 'Colis récupéré'), ('in_transit', 'En cours'), ('delivered', 'Livrée'), ('failed', 'Échec'), ('cancelled', 'Annulée')], default='waiting', max_length=20),
        ),
    ]
