# Generated by Django 5.2.8 on 2025-12-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_accepted_at_delivery_code_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='city',
            field=models.CharField(default='Libreville', help_text='Ville de livraison', max_length=100),
        ),
    ]
