# Generated by Django 5.2.8 on 2025-12-07 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_delivery_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin_number', models.CharField(blank=True, help_text='Numéro CIN ou ID interne', max_length=50)),
                ('vehicle_type', models.CharField(blank=True, help_text='Moto, Voiture, Vélo', max_length=50)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('busy', 'Occupé'), ('offline', 'Hors-ligne'), ('suspended', 'Suspendu')], default='offline', max_length=20)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Livreur',
                'verbose_name_plural': 'Profils Livreurs',
            },
        ),
    ]
