# Generated by Django 5.2.8 on 2025-12-08 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='client_name_confirmed',
            field=models.CharField(blank=True, help_text='Nom du réceptionnaire', max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='client_signature',
            field=models.ImageField(blank=True, help_text='Signature digitale du client', null=True, upload_to='delivery_signatures/'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='proof_address',
            field=models.CharField(blank=True, help_text='Adresse capturée au moment de la livraison', max_length=255),
        ),
        migrations.AddField(
            model_name='delivery',
            name='proof_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude au moment de la livraison', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='proof_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude au moment de la livraison', max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Photo de la livraison (obligatoire)', upload_to='delivery_proofs/%Y/%m/%d/')),
                ('photo_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude GPS au moment de la livraison', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude GPS au moment de la livraison', max_digits=9)),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='Précision GPS en mètres', max_digits=6, null=True)),
                ('address_at_delivery', models.CharField(blank=True, help_text='Adresse capturée via reverse geocoding', max_length=255)),
                ('signature', models.ImageField(blank=True, help_text='Signature digitale du client', null=True, upload_to='delivery_signatures/%Y/%m/%d/')),
                ('pin_code', models.CharField(blank=True, help_text='Code PIN de vérification', max_length=6)),
                ('pin_verified', models.BooleanField(default=False, help_text='Code PIN vérifié')),
                ('recipient_name', models.CharField(blank=True, help_text='Nom de la personne qui a reçu le colis', max_length=100)),
                ('recipient_phone', models.CharField(blank=True, help_text='Téléphone du réceptionnaire', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes ou remarques du livreur')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Raison du rejet si statut = rejected')),
                ('distance_from_address', models.DecimalField(blank=True, decimal_places=2, help_text='Distance en mètres entre GPS et adresse client', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.OneToOneField(help_text='Livraison associée', on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='delivery.delivery')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin qui a vérifié la preuve', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preuve de Livraison',
                'verbose_name_plural': 'Preuves de Livraison',
                'ordering': ['-created_at'],
            },
        ),
    ]
