# Generated by Django 5.2.8 on 2025-12-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_delivery_client_name_confirmed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryproof',
            old_name='photo_uploaded_at',
            new_name='id_card_photo_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='deliveryproof',
            name='photo',
        ),
        migrations.AddField(
            model_name='deliveryproof',
            name='client_received_status',
            field=models.BooleanField(default=True, help_text='Client confirme avoir reçu le colis'),
        ),
        migrations.AddField(
            model_name='deliveryproof',
            name='id_card_photo',
            field=models.ImageField(blank=True, help_text="Photo de la pièce d'identité du client (OBLIGATOIRE)", null=True, upload_to='delivery_proofs/id_cards/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='deliveryproof',
            name='package_photo',
            field=models.ImageField(blank=True, help_text='Photo du colis livré (optionnelle)', null=True, upload_to='delivery_proofs/packages/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='deliveryproof',
            name='package_photo_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
