# Generated by Django 5.2.9 on 2026-01-06 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_rename_photo_uploaded_at_deliveryproof_id_card_photo_uploaded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MOTO', 'Moto'), ('CAR', 'Petite Voiture'), ('VAN', 'Camionnette'), ('TRUCK', 'Camion')], help_text='Type de véhicule', max_length=20, unique=True)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, help_text='Poids maximum en kg', max_digits=8)),
                ('max_items', models.PositiveIntegerField(help_text="Nombre maximum d'articles (0 = illimité)")),
                ('max_distance_km', models.DecimalField(decimal_places=2, help_text='Distance maximum en km', max_digits=8)),
                ('allow_intercity', models.BooleanField(default=False, help_text='Autorisé pour livraison inter-ville')),
                ('base_price_intra_city', models.DecimalField(decimal_places=2, default=0.0, help_text='Prix de base intra-ville (FCFA)', max_digits=10)),
                ('price_per_km_intra_city', models.DecimalField(decimal_places=2, default=0.0, help_text='Prix par km intra-ville (FCFA)', max_digits=8)),
                ('base_price_inter_city', models.DecimalField(decimal_places=2, default=0.0, help_text='Prix de base inter-ville (FCFA)', max_digits=10)),
                ('price_per_km_inter_city', models.DecimalField(decimal_places=2, default=0.0, help_text='Prix par km inter-ville (FCFA)', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Type de véhicule actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de Véhicule',
                'verbose_name_plural': 'Types de Véhicules',
                'ordering': ['max_weight_kg'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='assignment_timeout_minutes',
            field=models.PositiveIntegerField(default=2, help_text='Timeout pour acceptation livreur (minutes)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance totale en km (store → client)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_intra_city',
            field=models.BooleanField(default=True, help_text='Livraison intra-ville (même ville)'),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='allow_intercity',
            field=models.BooleanField(default=False, help_text='Livreur autorisé pour livraisons inter-ville'),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='vehicle_type_old',
            field=models.CharField(blank=True, help_text='Ancien champ (migration) - Moto, Voiture, Vélo', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending_vehicle_validation', 'En attente validation véhicule'), ('awaiting_delivery_payment', 'En attente paiement livraison'), ('ready_for_assignment', 'Prête pour assignation'), ('waiting', "En attente d'assignation"), ('pending', "En attente d'acceptation"), ('assigned', 'Assignée'), ('accepted_by_driver', 'Acceptée par livreur'), ('accepted', 'Acceptée par livreur'), ('picked_up', 'Colis récupéré'), ('in_delivery', 'En cours de livraison'), ('in_transit', 'En cours'), ('delivered', 'Livrée'), ('failed', 'Échec'), ('cancelled', 'Annulée')], default='waiting', max_length=30),
        ),
        migrations.CreateModel(
            name='CityDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(help_text="Ville d'origine", max_length=100)),
                ('to_city', models.CharField(help_text='Ville de destination', max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance en km', max_digits=8)),
                ('estimated_time_minutes', models.PositiveIntegerField(help_text='Temps estimé en minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Distance entre Villes',
                'verbose_name_plural': 'Distances entre Villes',
                'indexes': [models.Index(fields=['from_city', 'to_city'], name='delivery_ci_from_ci_75b866_idx')],
                'unique_together': {('from_city', 'to_city')},
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='minimum_required_vehicle_type',
            field=models.ForeignKey(blank=True, help_text='Type de véhicule minimum requis (calculé automatiquement)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_deliveries', to='delivery.vehicletype'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='selected_vehicle_type',
            field=models.ForeignKey(blank=True, help_text='Type de véhicule sélectionné par le client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_deliveries', to='delivery.vehicletype'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, help_text='Type de véhicule utilisé (déduit du livreur)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.vehicletype'),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, help_text='Type de véhicule du livreur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_profiles', to='delivery.vehicletype'),
        ),
    ]
