# Generated by Django 5.2.9 on 2026-01-14 10:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_vehicletype_delivery_assignment_timeout_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la zone (ex: Centre-Ville, Louis, Mont-Bouët)', max_length=100, unique=True)),
                ('city', models.CharField(help_text='Ville (Libreville, Owendo, etc.)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Zone active pour les commandes')),
                ('description', models.TextField(blank=True, help_text='Description de la zone (localisation, quartiers)')),
                ('inter_city_surcharge', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Surcharge fixe pour livraison inter-ville (FCFA)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone de Livraison',
                'verbose_name_plural': 'Zones de Livraison',
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['is_active', 'city'], name='delivery_de_is_acti_7f4799_idx')],
            },
        ),
        migrations.CreateModel(
            name='ZoneVehicleRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Prix de base pour cette zone + véhicule (FCFA)', max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prix par km supplémentaire (FCFA/km)', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Tarif actif')),
                ('notes', models.TextField(blank=True, help_text='Notes (ex: tarif réduit, promo, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(help_text='Type de véhicule', on_delete=django.db.models.deletion.CASCADE, related_name='zone_rates', to='delivery.vehicletype')),
                ('zone', models.ForeignKey(help_text='Zone de livraison', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_rates', to='delivery.deliveryzone')),
            ],
            options={
                'verbose_name': 'Tarif Zone + Véhicule',
                'verbose_name_plural': 'Tarifs Zones + Véhicules',
                'ordering': ['zone', 'vehicle'],
                'indexes': [models.Index(fields=['zone', 'is_active'], name='delivery_zo_zone_id_5e3171_idx')],
                'unique_together': {('zone', 'vehicle')},
            },
        ),
    ]
