# Generated by Django 5.2.9 on 2026-01-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_deliveryzone_zonevehiclerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryzone',
            name='name',
            field=models.CharField(help_text='Nom de la zone (ex: Centre-Ville, Louis, Mont-Bouët)', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryzone',
            unique_together={('name', 'city')},
        ),
    ]
