# Generated by Django 5.2.8 on 2026-01-16 00:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_deliveryzone_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='max_length_m',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Longueur maximum en mètres', max_digits=6),
        ),
    ]
