# Generated by Django 5.2.17 on 2026-10-09 23:59

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0013_delivery_auto_assignment_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="client_signature",
            field=models.ImageField(
                blank=True,
                help_text="Signature digitale du client",
                null=True,
                storage=core.storage.private_storage,
                upload_to=core.storage.signature_path,
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="delivery_proof_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=core.storage.private_storage,
                upload_to=core.storage.delivery_photo_path,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryproof",
            name="id_card_photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo de la pièce d'identité du client (OBLIGATOIRE)",
                null=True,
                storage=core.storage.private_storage,
                upload_to=core.storage.id_card_photo_path,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryproof",
            name="package_photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo du colis livré (optionnelle)",
                null=True,
                storage=core.storage.private_storage,
                upload_to=core.storage.package_photo_path,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryproof",
            name="signature",
            field=models.ImageField(
                blank=True,
                help_text="Signature digitale du client",
                null=True,
                storage=core.storage.private_storage,
                upload_to=core.storage.signature_path,
            ),
        ),
    ]
