# Generated by Django 5.2.8 on 2025-11-26 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, help_text='Adresse complète du client')),
                ('city', models.CharField(blank=True, default='Libreville', max_length=100)),
                ('zone', models.CharField(blank=True, help_text='Zone/Quartier à Libreville', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('preferred_payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('card', 'Carte Bancaire'), ('cash', 'Espèces')], default='mobile_money', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Utilisateur',
                'verbose_name_plural': 'Profiles Utilisateurs',
            },
        ),
    ]
