# Generated by Django 5.2.8 on 2025-11-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional username; phone is used as the primary identifier', max_length=150, null=True),
        ),
    ]
