# Generated by Django 5.2.8 on 2025-12-04 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_principale', models.TextField(help_text='Adresse principale de livraison')),
                ('zone_principale', models.CharField(help_text='Zone à Libreville', max_length=100)),
                ('adresses_supplementaires', models.JSONField(blank=True, default=list, help_text="Liste d'adresses supplémentaires")),
                ('preferences_livraison', models.TextField(blank=True, help_text='Instructions de livraison par défaut')),
                ('total_commandes', models.PositiveIntegerField(default=0)),
                ('total_depense', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Client',
                'verbose_name_plural': 'Profils Clients',
            },
        ),
        migrations.CreateModel(
            name='GerantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_activite', models.DateField(blank=True, null=True)),
                ('documents_verification', models.JSONField(blank=True, default=dict, help_text='CNI, registre commerce, etc.')),
                ('total_ventes', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_commandes_recues', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gerant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Gérant',
                'verbose_name_plural': 'Profils Gérants',
            },
        ),
        migrations.CreateModel(
            name='LivreurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True, help_text='Livreur disponible pour assignation')),
                ('position_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('position_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_position_update', models.DateTimeField(blank=True, null=True)),
                ('type_vehicule', models.CharField(choices=[('moto', 'Moto'), ('scooter', 'Scooter'), ('velo', 'Vélo'), ('voiture', 'Voiture')], default='moto', max_length=20)),
                ('immatriculation', models.CharField(blank=True, max_length=50)),
                ('cni', models.CharField(blank=True, help_text='Numéro CNI', max_length=50)),
                ('permis', models.CharField(blank=True, help_text='Numéro permis de conduire', max_length=50)),
                ('documents_verifies', models.BooleanField(default=False)),
                ('total_livraisons', models.PositiveIntegerField(default=0)),
                ('livraisons_reussies', models.PositiveIntegerField(default=0)),
                ('livraisons_echouees', models.PositiveIntegerField(default=0)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, help_text='Note sur 5', max_digits=3)),
                ('total_revenus', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Livreur',
                'verbose_name_plural': 'Profils Livreurs',
                'indexes': [models.Index(fields=['disponible', 'position_lat', 'position_lng'], name='users_livre_disponi_666e6c_idx')],
            },
        ),
    ]
