# Generated by Django 5.2.8 on 2025-12-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_clientprofile_gerantprofile_livreurprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Libreville', help_text="Ville de résidence ou d'opération", max_length=100),
        ),
    ]
