# Generated by Django 5.2.8 on 2025-12-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Photo de profil', null=True, upload_to='profile_pics/'),
        ),
    ]
