# Generated by Django 5.2.8 on 2026-01-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_deliveryagentapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreurprofile',
            name='position_lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='livreurprofile',
            name='position_lng',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
