# Generated by Django 5.2.17 on 2026-10-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_create_missing_courier_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="livreurprofile",
            name="mobile_money_phone",
            field=models.CharField(
                blank=True,
                help_text="Numéro Mobile Money du livreur (+241...)",
                max_length=20,
            ),
        ),
    ]
