# Generated by Django 5.2 on 2026-01-03 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_alter_productcategory_unique_together_and_more'),
        ('stores', '0008_add_offers_delivery'),  # Dernière migration stores avant 0009
    ]

    operations = [
        migrations.CreateModel(
            name='B2BCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la catégorie B2B', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description de la catégorie')),
                ('is_active', models.BooleanField(default=True, help_text='La catégorie est-elle active ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie B2B',
                'verbose_name_plural': 'Catégories B2B',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='b2b_b2bcate_is_acti_602b87_idx')],
            },
        ),
        migrations.CreateModel(
            name='B2BProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b2b_price', models.DecimalField(decimal_places=2, help_text='Prix B2B en FCFA', max_digits=10)),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Quantité minimale pour ce prix (MOQ)')),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Quantité maximale pour ce prix (optionnel)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Ce prix B2B est-il actif ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('b2b_store', models.ForeignKey(help_text='Grossiste qui vend ce produit', on_delete=django.db.models.deletion.CASCADE, related_name='b2b_pricings', to='stores.store')),
                ('product', models.ForeignKey(help_text='Produit concerné', on_delete=django.db.models.deletion.CASCADE, related_name='b2b_pricings', to='products.product')),
            ],
            options={
                'verbose_name': 'Prix B2B',
                'verbose_name_plural': 'Prix B2B',
                'ordering': ['b2b_store', 'product', 'min_quantity'],
                'indexes': [models.Index(fields=['product', 'b2b_store', 'is_active'], name='b2b_b2bprod_product_446a36_idx'), models.Index(fields=['is_active'], name='b2b_b2bprod_is_acti_73c994_idx')],
                'unique_together': {('product', 'b2b_store', 'min_quantity')},
            },
        ),
        migrations.CreateModel(
            name='B2BProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Le profil B2B est-il actif ?')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant minimum de commande en FCFA', max_digits=10)),
                ('visible_to_all', models.BooleanField(default=True, help_text='Visible par tous les magasins B2C (sinon accès restreint)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(help_text='Magasin associé à ce profil B2B', on_delete=django.db.models.deletion.CASCADE, related_name='b2b_profile', to='stores.store')),
            ],
            options={
                'verbose_name': 'Profil B2B',
                'verbose_name_plural': 'Profils B2B',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'visible_to_all'], name='b2b_b2bprof_is_acti_ee0438_idx')],
            },
        ),
    ]
