# Generated by Django 5.2.9 on 2026-01-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0002_b2b_subscription_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2bsubscriptionplan',
            name='custom_features',
            field=models.JSONField(blank=True, default=list, help_text='Liste d\'avantages personnalisés au format JSON [{"title": "...", "description": "...", "enabled": true}]'),
        ),
    ]
