# Generated by Django 5.2 on 2026-01-04 20:20

from django.db import migrations, models


def migrate_has_advanced_analytics_to_detailed_reports(apps, schema_editor):
    """Migre has_advanced_analytics=True vers can_view_detailed_reports=True"""
    B2BSubscriptionPlan = apps.get_model('b2b', 'B2BSubscriptionPlan')
    B2BSubscriptionPlan.objects.filter(has_advanced_analytics=True).update(can_view_detailed_reports=True)


def reverse_migrate(apps, schema_editor):
    """Reverse: migre can_view_detailed_reports vers has_advanced_analytics"""
    B2BSubscriptionPlan = apps.get_model('b2b', 'B2BSubscriptionPlan')
    B2BSubscriptionPlan.objects.filter(can_view_detailed_reports=True).update(has_advanced_analytics=True)


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0003_alter_b2bsubscriptionplan_custom_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bsubscriptionplan',
            name='applies_to',
            field=models.CharField(choices=[('b2b_wholesaler', 'B2B Grossiste uniquement')], default='b2b_wholesaler', help_text="Type de magasin auquel ce plan s'applique", max_length=20),
        ),
        migrations.AddField(
            model_name='b2bsubscriptionplan',
            name='can_export_finance_csv',
            field=models.BooleanField(default=False, help_text='Peut exporter les rapports financiers en Excel/CSV'),
        ),
        migrations.AddField(
            model_name='b2bsubscriptionplan',
            name='can_export_finance_pdf',
            field=models.BooleanField(default=False, help_text='Peut exporter les rapports financiers en PDF officiel'),
        ),
        migrations.AddField(
            model_name='b2bsubscriptionplan',
            name='can_view_detailed_reports',
            field=models.BooleanField(default=False, help_text='Peut voir les détails par commande et par catégorie'),
        ),
        migrations.AddField(
            model_name='b2bsubscriptionplan',
            name='can_view_finance_basic',
            field=models.BooleanField(default=True, help_text='Peut voir les rapports financiers basiques (ventes du jour/mois)'),
        ),
        migrations.AddField(
            model_name='b2bsubscriptionplan',
            name='can_view_finance_detailed',
            field=models.BooleanField(default=False, help_text='Peut voir les détails financiers par commande et par catégorie'),
        ),
        migrations.AddField(
            model_name='b2bsubscriptionplan',
            name='finance_history_limit_days',
            field=models.IntegerField(blank=True, help_text="Limite d'historique financier en jours (null = illimité)", null=True),
        ),
        migrations.AlterField(
            model_name='b2bsubscriptionplan',
            name='catalog_priority',
            field=models.IntegerField(default=0, help_text="Priorité d'affichage dans le catalogue B2B (Distribution prioritaire)"),
        ),
        migrations.AlterField(
            model_name='b2bsubscriptionplan',
            name='featured_in_catalog',
            field=models.BooleanField(default=False, help_text='Référencé en tête du catalogue B2B (Grossiste recommandé)'),
        ),
        migrations.AlterField(
            model_name='b2bsubscriptionplan',
            name='has_advanced_analytics',
            field=models.BooleanField(default=False, help_text='Accès aux statistiques avancées B2B (déprécié, utiliser can_view_detailed_reports)'),
        ),
        migrations.RunPython(
            migrate_has_advanced_analytics_to_detailed_reports,
            reverse_migrate,
        ),
    ]
