# Generated by Django 5.2.9 on 2026-01-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0004_enhance_b2b_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2bstoresubscription',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix mensuel (rempli automatiquement)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='b2bstoresubscription',
            name='plan_name',
            field=models.CharField(blank=True, help_text='Nom du plan au moment de la souscription (rempli automatiquement)', max_length=100),
        ),
    ]
