FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update \
    && apt-get install -y build-essential gcc libpq-dev pkg-config libcairo2-dev --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r /app/requirements.txt

COPY . /app
RUN chmod +x /app/scripts/entrypoint.prod.sh

# Create staticfiles directory for production
RUN mkdir -p /app/staticfiles /app/media

EXPOSE 8000

CMD ["/app/scripts/entrypoint.prod.sh"]
