"""
Django settings for gaboshop project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from django.core.exceptions import ImproperlyConfigured

# Load .env values into process env for local/dev runs.
# Existing environment variables keep priority.
def _load_env_file(path):
    try:
        if not path.exists():
            return
        for raw_line in path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            line = line.lstrip("\ufeff")
            if not line or line.startswith("#"):
                continue
            if line.startswith("export "):
                line = line[len("export "):].strip()
            if "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            key = key.lstrip("\ufeff")
            if not key:
                continue
            value = value.strip()
            if (value.startswith('"') and value.endswith('"')) or (
                value.startswith("'") and value.endswith("'")
            ):
                value = value[1:-1]
            current = os.environ.get(key)
            if current is None or current == "":
                os.environ[key] = value
    except Exception:
        # Keep startup resilient even if .env is malformed.
        pass

_load_env_file(Path(__file__).resolve().parent / ".env")

# small helper to read environment variables in settings where a full
# django-environ or decouple isn't configured. Use real env library in prod.
def env(name, default=None):
    return os.environ.get(name, default)

def env_bool(name, default=False):
    value = env(name, None)
    if value is None:
        return default
    return str(value).lower() in ("1", "true", "yes", "on")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# This settings.py lives at the repository root, so BASE_DIR must be its
# parent (not parent.parent) to avoid resolving to "/" in Docker.
BASE_DIR = Path(__file__).resolve().parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", False)

# A secret must always come from the environment. This intentionally fails
# fast so a production process cannot start with Django's insecure fallback.
SECRET_KEY = env("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set.")

# Allow local hosts by default; override with DJANGO_ALLOWED_HOSTS
# 10.0.2.2 is how the Android emulator reaches the host machine.
_default_allowed_hosts = ["localhost", "127.0.0.1", "testserver", "web", "10.0.2.2"]
_allowed_hosts_env = env("DJANGO_ALLOWED_HOSTS", "")
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = _default_allowed_hosts
# Render injects the public hostname of the service
_render_host = env("RENDER_EXTERNAL_HOSTNAME", "")
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    # celery integration apps temporarily disabled for unit tests to avoid
    # importing celery during Django app registry setup because this
    # repository includes a local file named `celery.py` that shadows the
    # installed package. Enable these in production/dev environment.
    'django_celery_beat',
    'django_celery_results',

    # Local apps
    'api',
    'users',
    'stores',
    'products',
    'orders',
    'payments',
    'delivery',
    'notifications',
    'revenue',
    'core',
    'b2b',
    'finance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # Explicit path for SQLite to avoid accidentally using /db.sqlite3
        # when BASE_DIR is resolved differently across environments.
        'NAME': env('SQLITE_PATH', str(Path(__file__).resolve().parent / 'db.sqlite3')),
        'OPTIONS': {
            # Reduce transient "database is locked" errors under concurrent requests.
            'timeout': int(env('SQLITE_TIMEOUT', 20)),
        },
    }
}

# Hosted deployments provide DATABASE_URL (postgres://user:pass@host:port/name).
# Without it the SQLite configuration above is kept unchanged.
_database_url = env("DATABASE_URL", "")
if _database_url:
    from urllib.parse import urlparse, unquote
    _db = urlparse(_database_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _db.path.lstrip('/'),
            'USER': unquote(_db.username or ''),
            'PASSWORD': unquote(_db.password or ''),
            'HOST': _db.hostname,
            'PORT': _db.port or 5432,
            'CONN_MAX_AGE': 60,
            'OPTIONS': {'sslmode': env('DATABASE_SSLMODE', 'require')},
            # A mettre a 1 derriere un pooler en mode transaction (ex: Supabase port 6543)
            'DISABLE_SERVER_SIDE_CURSORS': env_bool('DATABASE_DISABLE_SERVER_SIDE_CURSORS', False),
        }
    }
elif env("DATABASE_HOST", ""):
    # Alternative sans URL (evite les erreurs de format / caracteres speciaux du mot de passe)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('DATABASE_NAME', 'postgres'),
            'USER': env('DATABASE_USER', ''),
            'PASSWORD': env('DATABASE_PASSWORD', ''),
            'HOST': env('DATABASE_HOST'),
            'PORT': env('DATABASE_PORT', '5432'),
            'CONN_MAX_AGE': 60,
            'OPTIONS': {'sslmode': env('DATABASE_SSLMODE', 'require')},
            'DISABLE_SERVER_SIDE_CURSORS': env_bool('DATABASE_DISABLE_SERVER_SIDE_CURSORS', False),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
] if (BASE_DIR / 'static').exists() else []

if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# === DRF CONFIGURATION ===
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.ApiKeyAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'EXCEPTION_HANDLER': 'api.v1.exceptions.custom_exception_handler',
}

# === JWT CONFIGURATION ===
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# CORS is opt-in in production. Define the public frontend origin with
# DJANGO_CORS_ALLOWED_ORIGINS (comma-separated) in the deployment environment.
_local_frontend_origins = [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
]
_cors_env = env("DJANGO_CORS_ALLOWED_ORIGINS", "")
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _cors_env.split(",") if origin.strip()]
if DEBUG and not CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = _local_frontend_origins
# The Capacitor Android/iOS shells load the bundled frontend from these
# origins. Set DJANGO_MOBILE_APP_ORIGINS="" to disable mobile access.
_mobile_env = env("DJANGO_MOBILE_APP_ORIGINS", "https://localhost,capacitor://localhost")
CORS_ALLOWED_ORIGINS += [o.strip() for o in _mobile_env.split(",") if o.strip() and o.strip() not in CORS_ALLOWED_ORIGINS]
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

# CSRF origins follow the same explicit production policy.
_csrf_env = env("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_env.split(",") if origin.strip()]
if DEBUG and not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = _local_frontend_origins

# Enable these only after HTTPS is terminated by the deployment proxy. The
# defaults keep the current HTTP-only Docker topology functional while making
# the required production controls configurable.
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", False)
if env_bool("DJANGO_BEHIND_PROXY", False):
    # TLS is terminated by the hosting proxy (Render, ...)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", SECURE_SSL_REDIRECT)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", SECURE_SSL_REDIRECT)
SECURE_HSTS_SECONDS = int(env("DJANGO_SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)

# === FILE UPLOADS ===
MEDIA_ROOT = BASE_DIR / 'media'
# Le site web et l'app Android sont sur d'autres adresses que l'API : une image
# doit avoir une adresse complète. Render fournit RENDER_EXTERNAL_URL tout seul.
PUBLIC_API_URL = (env("PUBLIC_API_URL", "") or env("RENDER_EXTERNAL_URL", "")).rstrip('/')
MEDIA_URL = f"{PUBLIC_API_URL}/media/" if PUBLIC_API_URL else '/media/'
# Sans stockage externe, l'API sert elle-même les fichiers envoyés (perdus à chaque
# redéploiement sur Render gratuit : configurer Supabase Storage ci-dessous).
SERVE_MEDIA = env_bool("DJANGO_SERVE_MEDIA", True)

# Supabase Storage (compatible S3) : les images survivent aux redéploiements.
# Variables à saisir dans Render, jamais dans le code :
#   SUPABASE_STORAGE_ENDPOINT   https://<projet>.supabase.co/storage/v1/s3
#   SUPABASE_STORAGE_BUCKET     nom d'un bucket public, ex. media
#   SUPABASE_STORAGE_ACCESS_KEY_ID / SUPABASE_STORAGE_SECRET_ACCESS_KEY
#   SUPABASE_STORAGE_REGION     région affichée dans Supabase (ex. eu-west-3)
SUPABASE_STORAGE_ENDPOINT = env("SUPABASE_STORAGE_ENDPOINT", "").rstrip('/')
SUPABASE_STORAGE_BUCKET = env("SUPABASE_STORAGE_BUCKET", "")
USE_SUPABASE_STORAGE = bool(
    SUPABASE_STORAGE_ENDPOINT and SUPABASE_STORAGE_BUCKET
    and env("SUPABASE_STORAGE_ACCESS_KEY_ID", "") and env("SUPABASE_STORAGE_SECRET_ACCESS_KEY", "")
)
if USE_SUPABASE_STORAGE:
    _public_base = SUPABASE_STORAGE_ENDPOINT.replace('/storage/v1/s3', '/storage/v1/object/public')
    STORAGES = {
        **globals().get('STORAGES', {"staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"}}),
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "endpoint_url": SUPABASE_STORAGE_ENDPOINT,
                "bucket_name": SUPABASE_STORAGE_BUCKET,
                "access_key": env("SUPABASE_STORAGE_ACCESS_KEY_ID", ""),
                "secret_key": env("SUPABASE_STORAGE_SECRET_ACCESS_KEY", ""),
                "region_name": env("SUPABASE_STORAGE_REGION", "us-east-1"),
                "signature_version": "s3v4",
                "addressing_style": "path",
                "querystring_auth": False,
                "file_overwrite": False,
                "custom_domain": f"{_public_base.split('://', 1)[1]}/{SUPABASE_STORAGE_BUCKET}",
            },
        },
    }
    MEDIA_URL = f"{_public_base}/{SUPABASE_STORAGE_BUCKET}/"
    SERVE_MEDIA = False

# Maximum file size for uploads (10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760

# Mobile Money APIs Configuration (Gabon)
AIRTEL_API_KEY = env('AIRTEL_API_KEY', default='')
AIRTEL_MERCHANT_ID = env('AIRTEL_MERCHANT_ID', default='')
AIRTEL_API_SECRET = env('AIRTEL_API_SECRET', default='')

MOOV_API_KEY = env('MOOV_API_KEY', default='')
MOOV_MERCHANT_ID = env('MOOV_MERCHANT_ID', default='')
MOOV_API_SECRET = env('MOOV_API_SECRET', default='')

# WhatsApp Business API
WHATSAPP_TOKEN = env('WHATSAPP_TOKEN', default='')
WHATSAPP_PHONE_ID = env('WHATSAPP_PHONE_ID', default='')

# Notifications / Messaging configuration
WHATSAPP_BUSINESS_API_URL = env('WHATSAPP_BUSINESS_API_URL', default='https://graph.facebook.com/v17.0')
WHATSAPP_PHONE_ID = env('WHATSAPP_PHONE_ID', default='')
WHATSAPP_ACCESS_TOKEN = env('WHATSAPP_ACCESS_TOKEN', default='')
WHATSAPP_VERIFY_TOKEN = env('WHATSAPP_VERIFY_TOKEN', default='gaboshop_webhook_2024')

# SMS Configuration
SMS_PROVIDER = env('SMS_PROVIDER', default='twilio')  # twilio, infobip, hub2
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = env('TWILIO_PHONE_NUMBER', default='')

# Hub2SMS Gabon Configuration
HUB2SMS_API_KEY = env('HUB2SMS_API_KEY', default='')
HUB2SMS_SENDER_ID = env('HUB2SMS_SENDER_ID', default='GABOSHOP')

# AI Provider Configuration
# Options: 'local', 'anthropic', 'deepseek', 'openai', 'groq', 'gemini'
# RECOMMANDÉ: 'groq' (gratuit, rapide) ou 'gemini' (gratuit, puissant)
AI_PROVIDER = env('AI_PROVIDER', default='groq')

# Anthropic Claude API Configuration
# Pour obtenir une clé: https://console.anthropic.com/
ANTHROPIC_API_KEY = env('ANTHROPIC_API_KEY', default='')
ANTHROPIC_MODEL = env('ANTHROPIC_MODEL', default='claude-3-5-sonnet-20241022')

# DeepSeek API Configuration (GRATUIT avec limites généreuses)
# Pour obtenir une clé: https://platform.deepseek.com/
# DeepSeek est GRATUIT avec 1M tokens/mois
DEEPSEEK_API_KEY = env('DEEPSEEK_API_KEY', default='')
DEEPSEEK_MODEL = env('DEEPSEEK_MODEL', default='deepseek-chat')
DEEPSEEK_BASE_URL = env('DEEPSEEK_BASE_URL', default='https://api.deepseek.com/v1')

# OpenAI API Configuration (payant, mais crédits gratuits au départ)
# Pour obtenir une clé: https://platform.openai.com/
OPENAI_API_KEY = env('OPENAI_API_KEY', default='')
OPENAI_MODEL = env('OPENAI_MODEL', default='gpt-3.5-turbo')

# Groq API Configuration (GRATUIT - 14,400 requêtes/jour)
# Pour obtenir une clé: https://console.groq.com/
# Groq est GRATUIT, ultra-rapide, pas de carte bancaire requise
GROQ_API_KEY = env('GROQ_API_KEY', default='')
GROQ_MODEL = env('GROQ_MODEL', default='llama-3.1-8b-instant')  # ou 'mixtral-8x7b-32768'

# Google Gemini API Configuration (GRATUIT - 1,500 requêtes/jour)
# Pour obtenir une clé: https://makersuite.google.com/app/apikey
# Gemini est GRATUIT, puissant, pas de carte bancaire requise initialement
GEMINI_API_KEY = env('GEMINI_API_KEY', default='')
GEMINI_MODEL = env('GEMINI_MODEL', default='models/gemini-2.0-flash')

# Email Configuration (optionnel)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='GABOSHOP <noreply@gaboshop.ga>')

# Templates de notifications
NOTIFICATION_TEMPLATES = {
    'new_order': {
        'whatsapp': 'nouvelle_commande',
        'sms': 'Nouvelle commande #{order_number} - {total_amount} FCFA - {client_phone}',
        'email': 'notifications/new_order.html'
    },
    'order_status_update': {
        'whatsapp': 'statut_commande', 
        'sms': 'Commande #{order_number}: {status}',
        'email': 'notifications/order_status.html'
    },
    'delivery_assigned': {
        'whatsapp': 'livraison_assignee',
        'sms': 'Nouvelle livraison #{tracking_number} - {delivery_fee} FCFA',
        'email': 'notifications/delivery_assigned.html'
    },
    'payment_success': {
        'whatsapp': 'paiement_confirme',
        'sms': 'Paiement confirmé - Commande #{order_number} - {amount} FCFA',
        'email': 'notifications/payment_success.html'
    },
    'payment_failed': {
        'whatsapp': 'paiement_echec',
        'sms': 'Paiement échoué - Commande #{order_number}',
        'email': 'notifications/payment_failed.html'
    }
}

# === CELERY CONFIGURATION ===
CELERY_BROKER_URL = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Libreville'
# Test deployments without a worker run tasks inline (no beat/worker needed).
CELERY_TASK_ALWAYS_EAGER = env_bool("CELERY_TASK_ALWAYS_EAGER", False)
CELERY_TASK_EAGER_PROPAGATES = False
CELERY_ENABLE_UTC = True

# Beat Schedule (tâches périodiques)
CELERY_BEAT_SCHEDULE = {
    'assigner-livreurs-toutes-les-5-min': {
        'task': 'orders.tasks.assigner_livreurs_automatique',
        'schedule': 300.0,  # 5 minutes
    },
    'nettoyer-paniers-abandonnes-toutes-les-heures': {
        'task': 'orders.tasks.nettoyer_paniers_abandonnes',
        'schedule': 3600.0,  # 1 heure
    },
    'verifier-paiements-en-attente-toutes-les-2-min': {
        'task': 'payments.tasks.verifier_paiements_en_attente',
        'schedule': 120.0,  # 2 minutes
    },
    'traiter-reversements-quotidien': {
        'task': 'payments.tasks.traiter_reversements_automatiques',
        'schedule': 86400.0,  # 24 heures
    },
    'envoyer-rapports-quotidien': {
        'task': 'notifications.tasks.envoyer_rapports_quotidiens',
        'schedule': 86400.0,  # 24 heures à 8h00
    },
}

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('REDIS_URL', default='redis://localhost:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# ============================================================================
# CINETPAY / AIRTEL MONEY / MOOV MONEY CONFIGURATION
# ============================================================================

# CinetPay Configuration
CINETPAY_API_URL = "https://api-checkout.cinetpay.com/v2/payment"
CINETPAY_CHECK_URL = "https://api-checkout.cinetpay.com/v2/payment/check"
CINETPAY_REFUND_URL = "https://api-checkout.cinetpay.com/v2/refund"
CINETPAY_SITE_ID = env("CINETPAY_SITE_ID", default="")
CINETPAY_APIKEY = env("CINETPAY_APIKEY", default="")
CINETPAY_SECRET = env("CINETPAY_SECRET", default="")
CINETPAY_NOTIFY_URL = env("CINETPAY_NOTIFY_URL", default="http://localhost:8000/api/v1/payments/provider/cinetpay/notify/")
CINETPAY_RETURN_URL = env("CINETPAY_RETURN_URL", default="http://localhost:3000/checkout/success")

# Airtel Money Configuration
AIRTEL_MERCHANT_ID = env("AIRTEL_MERCHANT_ID", default="")
AIRTEL_API_KEY = env("AIRTEL_API_KEY", default="")
AIRTEL_USSD_API_URL = "https://api.airtel.ga/v2/payment/request"
AIRTEL_CHECK_URL = "https://api.airtel.ga/v2/payment/status"

# Moov Money Configuration
MOOV_MERCHANT_ID = env("MOOV_MERCHANT_ID", default="")
MOOV_API_KEY = env("MOOV_API_KEY", default="")
MOOV_API_URL = "https://api.moov.ga/v1/payment/request"
MOOV_CHECK_URL = "https://api.moov.ga/v1/payment/status"

# SingPay Configuration
SINGPAY_BASE_URL = env('SINGPAY_BASE_URL', default='')
SINGPAY_CLIENT_ID = env('SINGPAY_CLIENT_ID', default='')
SINGPAY_CLIENT_SECRET = env('SINGPAY_CLIENT_SECRET', default='')
SINGPAY_WALLET_ID = env('SINGPAY_WALLET_ID', default='')
SINGPAY_DISBURSEMENT_ID = env('SINGPAY_DISBURSEMENT_ID', default='')
SINGPAY_TIMEOUT = env('SINGPAY_TIMEOUT', default='30')
SINGPAY_ENABLE_TRANSFER = env('SINGPAY_ENABLE_TRANSFER', default='False').lower() in ('1','true','yes')
PAYMENT_SIMULATION_MODE = env('PAYMENT_SIMULATION_MODE', default='False').lower() in ('1', 'true', 'yes')
PAYMENT_WEBHOOK_SECRET = env('PAYMENT_WEBHOOK_SECRET', default='')
PAYMENT_WEBHOOK_SIGNATURE_REQUIRED = env_bool(
    'PAYMENT_WEBHOOK_SIGNATURE_REQUIRED',
    default=not DEBUG,
)
