"""
Django settings for gaboshop project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# small helper to read environment variables in settings where a full
# django-environ or decouple isn't configured. Use real env library in prod.
def env(name, default=None):
    return os.environ.get(name, default)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(v504-88060g^)_%d!8n(6w$g^znk2d(9ezkp024t$hu(if5fu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Autoriser les requets locales (frontend React et API en dveloppement)
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    # celery integration apps temporarily disabled for unit tests to avoid
    # importing celery during Django app registry setup because this
    # repository includes a local file named `celery.py` that shadows the
    # installed package. Enable these in production/dev environment.
    'django_celery_beat',
    'django_celery_results',

    # Local apps
    'api',
    'users',
    'stores',
    'products',
    'orders',
    'payments',
    'delivery',
    'notifications',
    'revenue',
    'core',
    'b2b',
    'finance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gaboshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
] if (BASE_DIR / 'static').exists() else []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.ApiKeyAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Simple JWT settings (adjust lifetimes as needed)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS
# In development you can allow all origins. Lock this down for production.
CORS_ALLOW_ALL_ORIGINS = True
# Allow cookies (Authorization headers are allowed by default for JWT)
CORS_ALLOW_CREDENTIALS = True

# Example: whitelist specific origins in production instead of allowing all
# CORS_ALLOWED_ORIGINS = [
#     'https://example.com',
#     'https://sub.example.com',
# ]

# Custom user model
AUTH_USER_MODEL = 'users.User'

# === DRF CONFIGURATION ===
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'EXCEPTION_HANDLER': 'api.v1.exceptions.custom_exception_handler',
}

# === JWT CONFIGURATION ===
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# CORS Configuration
# In development allow all origins to avoid preflight CORS issues between
# the frontend dev server (Vite) and Django backend. Lock this down in
# production by setting CORS_ALLOW_ALL_ORIGINS = False and specifying
# CORS_ALLOWED_ORIGINS explicitly.
CORS_ALLOW_ALL_ORIGINS = True

# If you prefer to whitelist specific origins instead, uncomment and use:
# CORS_ALLOW_ALL_ORIGINS = False
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
# ]

# Trusted origins for CSRF (keep if you need cross-site POSTs during dev)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# === FILE UPLOADS ===
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Maximum file size for uploads (10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760

# Mobile Money APIs Configuration (Gabon)
AIRTEL_API_KEY = env('AIRTEL_API_KEY', default='')
AIRTEL_MERCHANT_ID = env('AIRTEL_MERCHANT_ID', default='')
AIRTEL_API_SECRET = env('AIRTEL_API_SECRET', default='')

MOOV_API_KEY = env('MOOV_API_KEY', default='')
MOOV_MERCHANT_ID = env('MOOV_MERCHANT_ID', default='')
MOOV_API_SECRET = env('MOOV_API_SECRET', default='')

# WhatsApp Business API
WHATSAPP_TOKEN = env('WHATSAPP_TOKEN', default='')
WHATSAPP_PHONE_ID = env('WHATSAPP_PHONE_ID', default='')

# Notifications / Messaging configuration
WHATSAPP_BUSINESS_API_URL = env('WHATSAPP_BUSINESS_API_URL', default='https://graph.facebook.com/v17.0')
WHATSAPP_PHONE_ID = env('WHATSAPP_PHONE_ID', default='')
WHATSAPP_ACCESS_TOKEN = env('WHATSAPP_ACCESS_TOKEN', default='')
WHATSAPP_VERIFY_TOKEN = env('WHATSAPP_VERIFY_TOKEN', default='gaboshop_webhook_2024')

# SMS Configuration
SMS_PROVIDER = env('SMS_PROVIDER', default='twilio')  # twilio, infobip, hub2
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = env('TWILIO_PHONE_NUMBER', default='')

# Hub2SMS Gabon Configuration
HUB2SMS_API_KEY = env('HUB2SMS_API_KEY', default='')
HUB2SMS_SENDER_ID = env('HUB2SMS_SENDER_ID', default='GABOSHOP')

# AI Provider Configuration
# Options: 'local', 'anthropic', 'deepseek', 'openai', 'groq', 'gemini'
# RECOMMANDÉ: 'groq' (gratuit, rapide) ou 'gemini' (gratuit, puissant)
AI_PROVIDER = env('AI_PROVIDER', default='groq')

# Anthropic Claude API Configuration
# Pour obtenir une clé: https://console.anthropic.com/
ANTHROPIC_API_KEY = env('ANTHROPIC_API_KEY', default='')
ANTHROPIC_MODEL = env('ANTHROPIC_MODEL', default='claude-3-5-sonnet-20241022')

# DeepSeek API Configuration (GRATUIT avec limites généreuses)
# Pour obtenir une clé: https://platform.deepseek.com/
# DeepSeek est GRATUIT avec 1M tokens/mois
DEEPSEEK_API_KEY = env('DEEPSEEK_API_KEY', default='sk-db6bf344ff014abfb68dd97f777b9146')
DEEPSEEK_MODEL = env('DEEPSEEK_MODEL', default='deepseek-chat')
DEEPSEEK_BASE_URL = env('DEEPSEEK_BASE_URL', default='https://api.deepseek.com/v1')

# OpenAI API Configuration (payant, mais crédits gratuits au départ)
# Pour obtenir une clé: https://platform.openai.com/
OPENAI_API_KEY = env('OPENAI_API_KEY', default='')
OPENAI_MODEL = env('OPENAI_MODEL', default='gpt-3.5-turbo')

# Groq API Configuration (GRATUIT - 14,400 requêtes/jour)
# Pour obtenir une clé: https://console.groq.com/
# Groq est GRATUIT, ultra-rapide, pas de carte bancaire requise
GROQ_API_KEY = env('GROQ_API_KEY', default='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')
GROQ_MODEL = env('GROQ_MODEL', default='llama-3.1-8b-instant')  # ou 'mixtral-8x7b-32768'

# Google Gemini API Configuration (GRATUIT - 1,500 requêtes/jour)
# Pour obtenir une clé: https://makersuite.google.com/app/apikey
# Gemini est GRATUIT, puissant, pas de carte bancaire requise initialement
GEMINI_API_KEY = env('GEMINI_API_KEY', default='AIzaSyBwD_d3-tR5rLFeDO3KKKqRUjd0-gIAAKc')
GEMINI_MODEL = env('GEMINI_MODEL', default='models/gemini-2.0-flash')

# Email Configuration (optionnel)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='GABOSHOP <noreply@gaboshop.ga>')

# Templates de notifications
NOTIFICATION_TEMPLATES = {
    'new_order': {
        'whatsapp': 'nouvelle_commande',
        'sms': 'Nouvelle commande #{order_number} - {total_amount} FCFA - {client_phone}',
        'email': 'notifications/new_order.html'
    },
    'order_status_update': {
        'whatsapp': 'statut_commande', 
        'sms': 'Commande #{order_number}: {status}',
        'email': 'notifications/order_status.html'
    },
    'delivery_assigned': {
        'whatsapp': 'livraison_assignee',
        'sms': 'Nouvelle livraison #{tracking_number} - {delivery_fee} FCFA',
        'email': 'notifications/delivery_assigned.html'
    },
    'payment_success': {
        'whatsapp': 'paiement_confirme',
        'sms': 'Paiement confirmé - Commande #{order_number} - {amount} FCFA',
        'email': 'notifications/payment_success.html'
    },
    'payment_failed': {
        'whatsapp': 'paiement_echec',
        'sms': 'Paiement échoué - Commande #{order_number}',
        'email': 'notifications/payment_failed.html'
    }
}

# === CELERY CONFIGURATION ===
CELERY_BROKER_URL = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Libreville'
CELERY_ENABLE_UTC = True

# Beat Schedule (tâches périodiques)
CELERY_BEAT_SCHEDULE = {
    'assigner-livreurs-toutes-les-5-min': {
        'task': 'orders.tasks.assigner_livreurs_automatique',
        'schedule': 300.0,  # 5 minutes
    },
    'nettoyer-paniers-abandonnes-toutes-les-heures': {
        'task': 'orders.tasks.nettoyer_paniers_abandonnes',
        'schedule': 3600.0,  # 1 heure
    },
    'verifier-paiements-en-attente-toutes-les-2-min': {
        'task': 'payments.tasks.verifier_paiements_en_attente',
        'schedule': 120.0,  # 2 minutes
    },
    'traiter-reversements-quotidien': {
        'task': 'payments.tasks.traiter_reversements_automatiques',
        'schedule': 86400.0,  # 24 heures
    },
    'envoyer-rapports-quotidien': {
        'task': 'notifications.tasks.envoyer_rapports_quotidiens',
        'schedule': 86400.0,  # 24 heures à 8h00
    },
}

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('REDIS_URL', default='redis://localhost:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# ============================================================================
# CINETPAY / AIRTEL MONEY / MOOV MONEY CONFIGURATION
# ============================================================================

# CinetPay Configuration
CINETPAY_API_URL = "https://api-checkout.cinetpay.com/v2/payment"
CINETPAY_CHECK_URL = "https://api-checkout.cinetpay.com/v2/payment/check"
CINETPAY_REFUND_URL = "https://api-checkout.cinetpay.com/v2/refund"
CINETPAY_SITE_ID = env("CINETPAY_SITE_ID", default="")
CINETPAY_APIKEY = env("CINETPAY_APIKEY", default="")
CINETPAY_SECRET = env("CINETPAY_SECRET", default="")
CINETPAY_NOTIFY_URL = env("CINETPAY_NOTIFY_URL", default="http://localhost:8000/api/v1/payments/provider/cinetpay/notify/")
CINETPAY_RETURN_URL = env("CINETPAY_RETURN_URL", default="http://localhost:3000/checkout/success")

# Airtel Money Configuration
AIRTEL_MERCHANT_ID = env("AIRTEL_MERCHANT_ID", default="")
AIRTEL_API_KEY = env("AIRTEL_API_KEY", default="")
AIRTEL_USSD_API_URL = "https://api.airtel.ga/v2/payment/request"
AIRTEL_CHECK_URL = "https://api.airtel.ga/v2/payment/status"

# Moov Money Configuration
MOOV_MERCHANT_ID = env("MOOV_MERCHANT_ID", default="")
MOOV_API_KEY = env("MOOV_API_KEY", default="")
MOOV_API_URL = "https://api.moov.ga/v1/payment/request"
MOOV_CHECK_URL = "https://api.moov.ga/v1/payment/status"
