# Generated by Django 5.2.8 on 2025-12-08 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('order_status_change', 'Changement de statut de commande'), ('delivery_status_change', 'Changement de statut de livraison'), ('order_created', 'Création de commande'), ('delivery_assigned', 'Attribution de livreur'), ('order_cancelled', 'Annulation de commande'), ('fraud_detected', 'Fraude potentielle détectée')], max_length=50)),
                ('action_timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_role', models.CharField(max_length=20)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('old_value', models.CharField(blank=True, max_length=100, null=True)),
                ('new_value', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True, help_text='Raison du changement')),
                ('is_suspicious', models.BooleanField(default=False, help_text='Marqué comme suspect par le système')),
                ('notes', models.TextField(blank=True, help_text="Notes de l'administrateur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-action_timestamp'],
                'indexes': [models.Index(fields=['action_timestamp', 'object_type'], name='core_auditl_action__bb3abc_idx'), models.Index(fields=['user', 'action_timestamp'], name='core_auditl_user_id_905268_idx'), models.Index(fields=['object_type', 'object_id'], name='core_auditl_object__42e4a9_idx'), models.Index(fields=['is_suspicious'], name='core_auditl_is_susp_c356bc_idx')],
            },
        ),
    ]
