# Generated by Django 5.2.8 on 2025-12-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('order_status_change', 'Changement de statut de commande'), ('delivery_status_change', 'Changement de statut de livraison'), ('order_created', 'Création de commande'), ('delivery_assigned', 'Attribution de livreur'), ('order_cancelled', 'Annulation de commande'), ('fraud_detected', 'Fraude potentielle détectée'), ('payment_initiated', 'Paiement initié'), ('payment_completed', 'Paiement confirmé'), ('payment_failed', 'Paiement échoué'), ('payment_refunded', 'Paiement remboursé'), ('store_created', 'Création de magasin'), ('store_updated', 'Mise à jour de magasin'), ('store_activated', 'Activation de magasin'), ('store_deactivated', 'Désactivation de magasin'), ('user_registered', 'Inscription utilisateur'), ('user_login', 'Connexion utilisateur'), ('user_profile_updated', 'Mise à jour profil'), ('user_password_changed', 'Changement de mot de passe'), ('commission_calculated', 'Commission calculée'), ('payout_processed', 'Paiement livreur traité'), ('subscription_created', 'Abonnement créé'), ('subscription_renewed', 'Abonnement renouvelé')], max_length=50),
        ),
    ]
