# Generated by Django 5.2 on 2026-01-04 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_is_b2b_order_source_store'),
        ('stores', '0010_alter_store_is_b2b_alter_store_is_b2c'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='stores.store')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('APPROVISIONNEMENT', 'Approvisionnement'), ('LOGISTIQUE', 'Logistique & Transport'), ('PERSONNEL', 'Personnel'), ('LOYER', 'Loyer & Charges'), ('MARKETING', 'Marketing & Publicité'), ('AUTRE', 'Autre')], max_length=30)),
                ('supplier_name', models.CharField(blank=True, help_text='Utilisé si supplier=null', max_length=255)),
                ('reference', models.CharField(blank=True, help_text='Facture, bon de commande, etc.', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('expense_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('MOMO', 'Mobile Money'), ('BANK_TRANSFER', 'Virement'), ('CHECK', 'Chèque'), ('CARD', 'Carte'), ('AUTRE', 'Autre')], max_length=20)),
                ('payment_status', models.CharField(choices=[('PAID', 'Payé'), ('PENDING', 'En attente'), ('PARTIAL', 'Partiel')], default='PAID', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('b2b_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_record', to='orders.order')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='stores.store')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.supplier')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['store', 'expense_date'], name='finance_exp_store_i_2ed3ff_idx'), models.Index(fields=['store', 'expense_type'], name='finance_exp_store_i_5db7a5_idx')],
            },
        ),
    ]
