# Generated by Django 5.2.8 on 2025-12-06 17:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0005_add_default_store_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_global', models.DecimalField(decimal_places=2, default=10.0, help_text='Commission globale par défaut (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('commission_event', models.DecimalField(decimal_places=2, default=5.0, help_text='Commission exceptionnelle pour événements/promos (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('moov_money_fee', models.DecimalField(decimal_places=2, default=1.5, help_text='Frais Moov Money (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('airtel_money_fee', models.DecimalField(decimal_places=2, default=1.5, help_text='Frais Airtel Money (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('payment_before_order', models.BooleanField(default=True, help_text='Paiement requis avant validation de commande')),
                ('unpaid_order_expiry_minutes', models.IntegerField(default=30, help_text="Délai max avant expiration d'une commande impayée (minutes)", validators=[django.core.validators.MinValueValidator(1)])),
                ('auto_detect_cities', models.BooleanField(default=True, help_text='Détection automatique des villes')),
                ('default_city', models.CharField(default='Abidjan', help_text='Ville par défaut', max_length=100)),
                ('enabled_cities', models.TextField(default='Abidjan,Bouaké,Yamoussoukro,San-Pedro,Korhogo', help_text='Liste des villes activées (séparées par des virgules)')),
                ('max_delivery_distance_km', models.DecimalField(decimal_places=2, default=50.0, help_text='Distance max de livraison (km)', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_km', models.DecimalField(decimal_places=2, default=200.0, help_text='Prix par km (FCFA)', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('auto_assign_delivery', models.BooleanField(default=False, help_text='Attribution automatique des livreurs')),
                ('max_orders_per_delivery', models.IntegerField(default=3, help_text='Max commandes simultanées par livreur', validators=[django.core.validators.MinValueValidator(1)])),
                ('cart_validity_hours', models.IntegerField(default=24, help_text="Durée de validité d'un panier (heures)", validators=[django.core.validators.MinValueValidator(1)])),
                ('order_opening_time', models.TimeField(default='08:00:00', help_text="Heure d'ouverture des commandes")),
                ('order_closing_time', models.TimeField(default='22:00:00', help_text='Heure de fermeture des commandes')),
                ('default_store_opening', models.TimeField(default='08:00:00', help_text="Heure d'ouverture par défaut des magasins")),
                ('default_store_closing', models.TimeField(default='20:00:00', help_text='Heure de fermeture par défaut des magasins')),
                ('store_verification_required', models.BooleanField(default=True, help_text='Vérification requise pour les nouveaux magasins')),
                ('pro_mode_monthly_fee', models.DecimalField(decimal_places=2, default=50000.0, help_text='Tarif mensuel Mode Pro (FCFA)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('enable_sms', models.BooleanField(default=True, help_text='Activer les notifications SMS')),
                ('enable_email', models.BooleanField(default=True, help_text='Activer les notifications Email')),
                ('notification_templates', models.JSONField(blank=True, default=dict, help_text='Templates de notifications personnalisés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre Système',
                'verbose_name_plural': 'Paramètres Système',
            },
        ),
        migrations.CreateModel(
            name='CommissionByCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Taux de commission pour cette catégorie (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='stores.storecategory')),
            ],
            options={
                'verbose_name': 'Commission par Catégorie',
                'verbose_name_plural': 'Commissions par Catégorie',
                'unique_together': {('category',)},
            },
        ),
    ]
