# Generated by Django 5.2.9 on 2026-01-05 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(default='AI', help_text="Toujours 'AI'", max_length=20)),
                ('action', models.CharField(choices=[('search', 'Recherche'), ('prepare_order', 'Préparation commande'), ('confirm_order', 'Confirmation commande'), ('explain_error', 'Explication erreur'), ('suggest_action', 'Suggestion action'), ('trigger_alert', 'Déclenchement alerte')], max_length=50)),
                ('details', models.JSONField(default=dict, help_text="Détails de l'action (produits, montants, etc.)")),
                ('confirmed', models.BooleanField(default=False, help_text="Action confirmée par l'utilisateur")),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('initiator', models.ForeignKey(help_text="Utilisateur qui a initié l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Action IA',
                'verbose_name_plural': 'Logs Actions IA',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'action'], name='api_aiactio_timesta_73bbd2_idx'), models.Index(fields=['initiator', 'timestamp'], name='api_aiactio_initiat_037b0f_idx'), models.Index(fields=['confirmed'], name='api_aiactio_confirm_a35b8d_idx')],
            },
        ),
    ]
