# Generated by Django 5.2.17 on 2026-10-09 10:19

import django.core.validators
from django.db import migrations, models


GABON_CITIES = "Libreville,Akanda,Owendo,Ntoum,Port-Gentil,Franceville,Moanda,Oyem,Lambaréné,Mouila"


def use_gabon_values(apps, schema_editor):
    """Remplace les valeurs d'origine (Côte d'Ivoire) et garde le comportement actuel des commerces."""
    SystemSettings = apps.get_model('api', 'SystemSettings')
    for row in SystemSettings.objects.all():
        if row.default_city == 'Abidjan':
            row.default_city = 'Libreville'
        if 'Abidjan' in (row.enabled_cities or ''):
            row.enabled_cities = GABON_CITIES
        # Jusqu'ici, ce réglage n'avait aucun effet : les nouveaux commerces étaient actifs tout de suite.
        row.store_verification_required = False
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_systemsettings_payment_policy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="auto_detect_cities",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="commission_event",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="max_delivery_distance_km",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="notification_templates",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="payment_before_order",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="price_per_km",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="pro_mode_monthly_fee",
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="enable_whatsapp",
            field=models.BooleanField(
                default=True, help_text="Activer les notifications WhatsApp"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="order_hours_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Limiter les commandes à une plage horaire commune à toute l'app",
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="cart_validity_hours",
            field=models.IntegerField(
                default=24,
                help_text="Une commande toujours en attente est annulée après ce délai (heures)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="default_city",
            field=models.CharField(
                default="Libreville", help_text="Ville par défaut", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="enabled_cities",
            field=models.TextField(
                default="Libreville,Akanda,Owendo,Ntoum,Port-Gentil,Franceville,Moanda,Oyem,Lambaréné,Mouila",
                help_text="Liste des villes activées (séparées par des virgules)",
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="max_orders_per_delivery",
            field=models.IntegerField(
                default=3,
                help_text="Nombre max de livraisons en cours par livreur avant de lui en proposer une autre",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="store_verification_required",
            field=models.BooleanField(
                default=False,
                help_text="Un nouveau commerce reste désactivé tant que l'admin ne l'a pas activé",
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="unpaid_order_expiry_minutes",
            field=models.IntegerField(
                default=30,
                help_text="Durée de validité d'une demande de paiement en ligne (minutes)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.RunPython(use_gabon_values, migrations.RunPython.noop),
    ]
