# Generated by Django 5.2.17 on 2026-10-09 10:30

import django.core.validators
from django.db import migrations, models


def align_default_commission(apps, schema_editor):
    """La commission globale (10 %) n'était lue nulle part : les commerces et catégories avaient 8 %.
    On aligne la valeur affichée sur ce qui s'appliquait vraiment."""
    SystemSettings = apps.get_model('api', 'SystemSettings')
    SystemSettings.objects.filter(commission_global=10).update(commission_global=8)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_settings_for_gabon"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="assignment_retry_minutes",
            field=models.IntegerField(
                default=5,
                help_text="Quand aucun livreur n'est libre, nouvel essai après (minutes)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="assignment_timeout_minutes",
            field=models.IntegerField(
                default=10,
                help_text="Temps laissé à un livreur pour accepter une course avant de la proposer au suivant (minutes)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="b2b_commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Commission de base sur une commande entre commerces (B2B), avant réduction du plan (%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="broadcast_after_minutes",
            field=models.IntegerField(
                default=40,
                help_text="Sans livreur après ce délai, la course est proposée à tous les livreurs (minutes)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="business_b2b_commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                help_text="Plan Business : commission sur les commandes B2B (%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="business_food_commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Plan Business : commission sur l'alimentaire vendu aux clients (%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="business_other_commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                help_text="Plan Business : commission sur le reste vendu aux clients (%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="courier_share_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=80.0,
                help_text="Part des frais de livraison versée au livreur ; le reste revient à Gaboshop (%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="food_category_keywords",
            field=models.CharField(
                default="ALIMENTATION,BOISSONS",
                help_text="Mots qui font compter une catégorie de commerce comme alimentaire (séparés par des virgules)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="late_delivery_hours",
            field=models.IntegerField(
                default=2,
                help_text="Une livraison en route depuis plus longtemps est signalée en retard (heures)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="max_rejected_declarations",
            field=models.IntegerField(
                default=3,
                help_text="Déclarations de paiement refusées avant blocage des nouvelles déclarations",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="pending_reminder_hours",
            field=models.IntegerField(
                default=1,
                help_text="Rappel au client pour une commande toujours en attente après (heures)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="pin_lock_minutes",
            field=models.IntegerField(
                default=30,
                help_text="Durée du blocage après trop de codes PIN erronés (minutes)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="pin_max_attempts",
            field=models.IntegerField(
                default=5,
                help_text="Codes PIN de livraison erronés avant blocage",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="rejected_window_days",
            field=models.IntegerField(
                default=30,
                help_text="Période sur laquelle les déclarations refusées sont comptées (jours)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="subscription_days",
            field=models.IntegerField(
                default=30,
                help_text="Durée d'un abonnement payé (jours)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="subscription_reminder_days",
            field=models.IntegerField(
                default=7,
                help_text="Rappel avant la fin d'un abonnement (jours)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="commission_global",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Commission par défaut d'un nouveau commerce ou d'une nouvelle catégorie (%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.RunPython(align_default_commission, migrations.RunPython.noop),
    ]
