# Generated by Django 5.2.17 on 2026-10-09 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_business_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="default_delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=2000.0,
                help_text="Frais de livraison standard d'un nouveau commerce, utilisés quand aucune zone ne correspond (FCFA)",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="default_express_delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=3500.0,
                help_text="Frais de livraison express d'un nouveau commerce (FCFA)",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="default_intercity_surcharge",
            field=models.DecimalField(
                decimal_places=2,
                default=1000.0,
                help_text="Supplément quand le client est dans une autre ville que le commerce et qu'aucune zone ne le précise (FCFA)",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
