# Generated by Django 5.2.17 on 2026-10-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_delivery_fee_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="ai_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Utiliser l'IA en ligne ; désactivée, l'assistant répond avec son moteur intégré",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="ai_instructions",
            field=models.TextField(
                blank=True,
                help_text="Consignes ajoutées à l'assistant (ton, promotions du moment, sujets à éviter…)",
                max_length=2000,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="ai_model",
            field=models.CharField(
                blank=True,
                help_text="Modèle (vide = modèle par défaut du fournisseur)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="ai_provider",
            field=models.CharField(
                blank=True,
                help_text="Fournisseur d'IA (vide = celui de Render). Sa clé doit être dans Render.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="company_address",
            field=models.CharField(
                blank=True, help_text="Adresse du siège", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="company_city",
            field=models.CharField(
                default="Libreville, Gabon", help_text="Ville du siège", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="company_legal_form",
            field=models.CharField(
                blank=True, help_text="Forme juridique (SARL, SA…)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="company_name",
            field=models.CharField(
                blank=True, help_text="Raison sociale", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="company_nif",
            field=models.CharField(blank=True, help_text="NIF", max_length=100),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="company_rccm",
            field=models.CharField(blank=True, help_text="Numéro RCCM", max_length=100),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="publication_director",
            field=models.CharField(
                blank=True, help_text="Directeur de la publication", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="support_email",
            field=models.EmailField(
                blank=True,
                default="support@gaboshop.ga",
                help_text="E-mail du support",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="support_phone",
            field=models.CharField(
                blank=True, help_text="Téléphone du support", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="support_whatsapp",
            field=models.CharField(
                blank=True, help_text="WhatsApp du support", max_length=30
            ),
        ),
    ]
