# Generated by Django 5.2.17 on 2026-10-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_company_and_ai"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="company_trade_name",
            field=models.CharField(
                default="Gaboshop",
                help_text="Nom commercial (affiché partout)",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="company_legal_form",
            field=models.CharField(
                blank=True, help_text="Forme juridique déposée au GNI", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Nom / identité juridique, exactement comme sur le document d'immatriculation",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="company_nif",
            field=models.CharField(
                blank=True,
                help_text="NIF (vide tant qu'il n'est pas attribué)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="company_rccm",
            field=models.CharField(
                blank=True,
                help_text="Numéro RCCM (vide tant que non immatriculée)",
                max_length=100,
            ),
        ),
    ]
