# Generated by Django 5.2.8 on 2025-12-04 22:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_commission_amount_order_commission_rate_and_more'),
        ('stores', '0002_store_delivery_fee_express_store_service_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link', models.URLField(blank=True, help_text='Lien de redirection (interne ou externe)')),
                ('position', models.CharField(choices=[('home_top', 'Accueil - Haut'), ('home_middle', 'Accueil - Milieu'), ('category_top', 'Catégorie - Haut'), ('search_result', 'Résultat de recherche')], default='home_top', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('price_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='stores.store')),
            ],
            options={
                'verbose_name': 'Publicité',
                'verbose_name_plural': 'Publicités',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(help_text='Raison du cashback (ex: Fidélité commande #123)', max_length=200)),
                ('is_credit', models.BooleanField(default=True, help_text='True = Gain, False = Utilisation')),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cashback', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cashback',
                'verbose_name_plural': 'Historique Cashback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('starter', 'Starter (Gratuit)'), ('pro', 'Pro (10.000 FCFA/mois)'), ('business', 'Business (30.000 FCFA/mois)')], default='starter', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='stores.store')),
            ],
            options={
                'verbose_name': 'Abonnement Magasin',
                'verbose_name_plural': 'Abonnements Magasins',
            },
        ),
    ]
