# Generated by Django 5.2.8 on 2025-11-26 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icône FontAwesome ou autre', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de Magasin',
                'verbose_name_plural': 'Catégories de Magasins',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('zone', models.CharField(help_text='Zone à Libreville: Mont-Bouët, Louis, etc.', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15.0, help_text='Commission de GABOSHOP en %', max_digits=5)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=1000.0, help_text='Frais de livraison standard en FCFA', max_digits=8)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Montant minimum de commande en FCFA', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('opening_time', models.TimeField(default='08:00')),
                ('closing_time', models.TimeField(default='20:00')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='stores/banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(limit_choices_to={'user_type': 'store_manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_stores', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stores.storecategory')),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['zone', 'is_active'], name='stores_stor_zone_cae260_idx'), models.Index(fields=['category', 'is_active'], name='stores_stor_categor_07ebf9_idx')],
            },
        ),
    ]
