# Generated by Django 5.2.8 on 2025-12-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='delivery_fee_express',
            field=models.DecimalField(decimal_places=2, default=3500.0, help_text='Frais de livraison express en FCFA', max_digits=8),
        ),
        migrations.AddField(
            model_name='store',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Frais de service par commande (optionnel)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='store',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Commission de GABOSHOP en % (défaut 8%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='store',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text='Frais de livraison standard en FCFA', max_digits=8),
        ),
    ]
