# Generated by Django 5.2.8 on 2025-12-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_delivery_fee_express_store_service_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(default='Libreville', help_text='Ville du magasin', max_length=100),
        ),
    ]
