# Generated by Django 5.2.8 on 2025-12-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(help_text='Numéro unique par magasin', max_length=20, unique=True),
        ),
    ]
