# Generated by Django 5.2.8 on 2025-12-06 16:43

from django.db import migrations


def add_default_categories(apps, schema_editor):
    StoreCategory = apps.get_model('stores', 'StoreCategory')
    categories = [
        "Hyper Marché",
        "Super Marché",
        "Mall",
        "ALIMENTATION & BOISSONS",
        "MODE & TEXTILE",
        "BEAUTÉ & SANTÉ",
        "MAISON & DÉCORATION",
        "ÉLECTRONIQUE & INFORMATIQUE",
        "ENFANTS & PUÉRICULTURE",
        "LOISIRS & CULTURE",
        "SERVICES LOCAUX",
    ]
    
    for name in categories:
        StoreCategory.objects.get_or_create(
            name=name,
            defaults={"description": "", "icon": "", "is_active": True}
        )


def reverse_default_categories(apps, schema_editor):
    StoreCategory = apps.get_model('stores', 'StoreCategory')
    categories = [
        "Hyper Marché",
        "Super Marché",
        "Mall",
        "ALIMENTATION & BOISSONS",
        "MODE & TEXTILE",
        "BEAUTÉ & SANTÉ",
        "MAISON & DÉCORATION",
        "ÉLECTRONIQUE & INFORMATIQUE",
        "ENFANTS & PUÉRICULTURE",
        "LOISIRS & CULTURE",
        "SERVICES LOCAUX",
    ]
    StoreCategory.objects.filter(name__in=categories).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_store_phone'),
    ]

    operations = [
        migrations.RunPython(add_default_categories, reverse_default_categories),
    ]

