# Generated by Django 5.2.8 on 2025-12-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_add_default_store_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='subscription_plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business')], default='starter', help_text="Plan d'abonnement du magasin", max_length=20),
        ),
    ]
