# Generated by Django 5.2.8 on 2025-12-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('retail', 'Détail (B2C)'), ('wholesaler', 'Grossiste (B2B)'), ('industry', 'Industrie (B2B)')], default='retail', help_text='Type de magasin: Détail (pour clients), Grossiste/Industrie (pour gérants)', max_length=20),
        ),
    ]
