# Generated by assistant on 2025-12-25
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_store_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='offers_delivery',
            field=models.BooleanField(default=False, help_text="Le magasin gère-t-il la livraison ? (par défaut: non)"),
        ),
    ]
