# Generated by Django 5.2 on 2026-01-03 15:22

from django.db import migrations, models


def migrate_store_type_to_b2c_b2b(apps, schema_editor):
    """
    Migre les données de store_type vers is_b2c/is_b2b
    """
    Store = apps.get_model('stores', 'Store')
    
    for store in Store.objects.all():
        if store.store_type == 'retail':
            store.is_b2c = True
            store.is_b2b = False
        elif store.store_type in ['wholesaler', 'industry']:
            store.is_b2c = False
            store.is_b2b = True
        else:
            # Par défaut, B2C seulement
            store.is_b2c = True
            store.is_b2b = False
        store.save()


def reverse_migrate(apps, schema_editor):
    """
    Reverse migration - ne fait rien car on ne peut pas déduire store_type
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_add_offers_delivery'),
    ]

    operations = [
        # Ajouter les champs is_b2c et is_b2b
        migrations.AddField(
            model_name='store',
            name='is_b2c',
            field=models.BooleanField(default=True, help_text='Le magasin peut-il vendre au détail (B2C) ?'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_b2b',
            field=models.BooleanField(default=False, help_text='Le magasin peut-il vendre en gros (B2B) ?'),
        ),
        # Ajouter les options B2B
        migrations.AddField(
            model_name='store',
            name='b2b_min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant minimum de commande B2B en FCFA', max_digits=10),
        ),
        migrations.AddField(
            model_name='store',
            name='b2b_delivery_delay',
            field=models.PositiveIntegerField(default=24, help_text='Délai de livraison B2B en heures'),
        ),
        # Migrer les données
        migrations.RunPython(migrate_store_type_to_b2c_b2b, reverse_migrate),
    ]
