# Generated by Django 5.2 on 2026-01-03 15:22
# Modified to depend on 0009_add_b2b_flags and only run data migration

from django.db import migrations


def migrate_store_type_to_b2c_b2b(apps, schema_editor):
    """
    Migre les données de store_type vers is_b2c/is_b2b
    Les champs ont déjà été ajoutés par 0009_add_b2b_flags
    """
    Store = apps.get_model('stores', 'Store')
    
    for store in Store.objects.all():
        if store.store_type == 'retail':
            store.is_b2c = True
            store.is_b2b = False
        elif store.store_type in ['wholesaler', 'industry']:
            store.is_b2c = False
            store.is_b2b = True
        else:
            # Par défaut, B2C seulement
            store.is_b2c = True
            store.is_b2b = False
        store.save()


def reverse_migrate(apps, schema_editor):
    """
    Reverse migration - ne fait rien car on ne peut pas déduire store_type
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_add_b2b_flags'),  # Dépend de la migration qui a ajouté les champs
    ]

    operations = [
        # Les champs ont déjà été ajoutés par 0009_add_b2b_flags
        # On fait seulement la migration de données
        migrations.RunPython(migrate_store_type_to_b2c_b2b, reverse_migrate),
    ]
