# Generated by Django 5.2.9 on 2026-01-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_add_offers_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='b2b_delivery_delay',
            field=models.PositiveIntegerField(default=24, help_text='Délai de livraison B2B en heures'),
        ),
        migrations.AddField(
            model_name='store',
            name='b2b_min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant minimum de commande B2B en FCFA', max_digits=10),
        ),
        migrations.AddField(
            model_name='store',
            name='is_b2b',
            field=models.BooleanField(default=False, help_text="Le magasin peut vendre à d'autres magasins (grossiste)"),
        ),
        migrations.AddField(
            model_name='store',
            name='is_b2c',
            field=models.BooleanField(default=True, help_text='Le magasin peut vendre à des clients finaux'),
        ),
    ]
