# Generated by Django 5.2 on 2026-01-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_add_b2c_b2b_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_b2b',
            field=models.BooleanField(default=False, help_text="Le magasin peut vendre à d'autres magasins (grossiste)"),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_b2c',
            field=models.BooleanField(default=True, help_text='Le magasin peut vendre à des clients finaux'),
        ),
    ]
