# Generated by Django 5.2.9 on 2026-01-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_alter_store_is_b2b_alter_store_is_b2c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_b2b',
            field=models.BooleanField(default=False, help_text='Le magasin peut-il vendre en gros (B2B) ?'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_b2c',
            field=models.BooleanField(default=True, help_text='Le magasin peut-il vendre au détail (B2C) ?'),
        ),
    ]
