# Generated by Django 6.0.3 on 2026-03-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_store_is_b2b_alter_store_is_b2c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Champ desactive (laisser a 0)', max_digits=8),
        ),
    ]
