# Generated by Django 5.2.17 on 2026-10-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0014_store_agent_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="payout_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Numéro Mobile Money du commerce pour recevoir ses ventes (Airtel 07…, Moov 06…)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="singpay_disbursement_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Identifiant de décaissement SingPay du commerce (créé par Gaboshop dans l'espace marchand SingPay)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="agent_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Code agent Mobile Money indiqué par le commerce pour recevoir ses ventes",
                max_length=100,
            ),
        ),
    ]
