# Generated by Django 5.2.17 on 2026-10-09 10:20

import stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0015_store_payout_destination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="closing_time",
            field=models.TimeField(default=stores.models.default_closing_time),
        ),
        migrations.AlterField(
            model_name="store",
            name="opening_time",
            field=models.TimeField(default=stores.models.default_opening_time),
        ),
    ]
