# Generated by Django 5.2.17 on 2026-10-09 10:31

import stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0016_store_hours_from_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=stores.models.default_commission_rate,
                help_text="Commission de GABOSHOP en % (défaut 8%)",
                max_digits=5,
            ),
        ),
    ]
