# Generated by Django 5.2.17 on 2026-10-09 10:39

import stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0017_default_commission_from_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=stores.models.default_delivery_fee,
                help_text="Frais de livraison standard en FCFA",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="delivery_fee_express",
            field=models.DecimalField(
                decimal_places=2,
                default=stores.models.default_express_delivery_fee,
                help_text="Frais de livraison express en FCFA",
                max_digits=8,
            ),
        ),
    ]
