# Generated by Django 5.2.8 on 2025-12-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission GABOSHOP', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Taux de commission en %', max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('standard', 'Standard (2-3h)'), ('express', 'Express (1h)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Frais de service plateforme', max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Frais de livraison', max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sous-total produits', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', '🟡 Créée'), ('pending_payment', '🟡 En attente de paiement'), ('paid', '🟢 Payée'), ('confirmed', '🔵 Confirmée'), ('preparing', '👨\u200d🍳 En préparation'), ('ready', '✅ Prête pour livraison'), ('assigned', '🚗 Livreur assigné'), ('in_transit', '📦 En cours de livraison'), ('delivered', '🎉 Livrée'), ('cancelled', '❌ Annulée'), ('refunded', '💸 Remboursée')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taxes (optionnel)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total à payer', max_digits=10),
        ),
    ]
