# Generated by Django 5.2.8 on 2025-12-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_commission_amount_order_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Libreville', help_text='Ville de livraison', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Frais de transaction (Mobile Money)', max_digits=8),
        ),
    ]
