# Generated by Django 5.2.8 on 2025-12-12 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_city_order_payment_fees'),
        ('stores', '0007_store_store_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_b2b',
            field=models.BooleanField(default=False, help_text='Commande entre professionnels (Store à Store)'),
        ),
        migrations.AddField(
            model_name='order',
            name='source_store',
            field=models.ForeignKey(blank=True, help_text='Magasin qui a passé la commande (si B2B)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_orders', to='stores.store'),
        ),
    ]
