# Generated by Django 5.2.8 on 2026-01-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_b2b_order_source_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='operator_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Frais opérateur Mobile Money (Airtel/Moov)', max_digits=8),
        ),
    ]
