# Generated by Django 5.2.9 on 2026-01-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_operator_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Coût calculé de la livraison selon ville et véhicule', max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_requested',
            field=models.BooleanField(default=True, help_text='Le client souhaite-t-il être livré ? (ON par défaut)'),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='Type de véhicule assigné selon le poids', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Frais de livraison (calculés)', max_digits=8),
        ),
    ]
