# Generated by Django 6.0.3 on 2026-03-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivery_cost_order_delivery_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Champ desactive (laisser a 0)', max_digits=8),
        ),
    ]
