# Generated by Django 5.2 on 2026-09-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_service_fee'),
        ('stores', '0012_alter_store_service_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Co\u00c3\u00bbt calcul\u00c3\u00a9 de la livraison selon ville et v\u00c3\u00a9hicule', max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Frais de livraison (calcul\u00c3\u00a9s)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_requested',
            field=models.BooleanField(default=True, help_text='Le client souhaite-t-il \u00c3\u00aatre livr\u00c3\u00a9 ? (ON par d\u00c3\u00a9faut)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_b2b',
            field=models.BooleanField(default=False, help_text='Commande entre professionnels (Store ' + '\xc3' + r'\xa0 Store)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Instructions sp\u00c3\u00a9ciales du client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operator_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Frais op\u00c3\u00a9rateur Mobile Money (Airtel/Moov)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_store',
            field=models.ForeignKey(blank=True, help_text='Magasin qui a pass\u00c3\u00a9 la commande (si B2B)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_orders', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', '?? Cr\u00c3\u00a9\u00c3\u00a9e'), ('pending_payment', '?? En attente de paiement'), ('paid', '?? Pay\u00c3\u00a9e'), ('confirmed', '?? Confirm\u00c3\u00a9e'), ('preparing', '????? En pr\u00c3\u00a9paration'), ('ready', '? Pr\u00c3\u00aate pour livraison'), ('assigned', '?? Livreur assign\u00c3\u00a9'), ('in_transit', '?? En cours de livraison'), ('delivered', '?? Livr\u00c3\u00a9e'), ('cancelled', '? Annul\u00c3\u00a9e'), ('refunded', '?? Rembours\u00c3\u00a9e')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total ' + '\xc3' + r'\xa0 payer', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='Type de v\u00c3\u00a9hicule assign\u00c3\u00a9 selon le poids', max_length=50, null=True),
        ),
    ]
