# Generated by Django 5.2 on 2026-10-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_delivery_cost_alter_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_b2b',
            field=models.BooleanField(default=False, help_text='Commande entre professionnels (Store Ã\xa0 Store)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total Ã\xa0 payer', max_digits=10),
        ),
    ]
