# Generated by Django 5.2.8 on 2025-12-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sponsored',
            field=models.BooleanField(default=False, help_text='Produit sponsorisé (affiché en priorité)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sponsor_expiry',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration du sponsoring", null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sponsor_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix payé pour le sponsoring', max_digits=10),
        ),
    ]
