# Generated by Django 5.2.9 on 2025-12-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_variants_and_images'),
        ('stores', '0007_store_store_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('store_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category_templates', to='stores.storecategory')),
            ],
            options={
                'verbose_name': 'Template Catégorie Produit',
                'verbose_name_plural': 'Templates Catégories Produits',
                'ordering': ['order', 'name'],
                'unique_together': {('store_category', 'name')},
            },
        ),
    ]
