# Generated by Django 5.2.9 on 2025-12-25 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_make_store_nullable'),
        ('stores', '0008_add_offers_delivery'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='store_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_categories', to='stores.storecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('store_category', 'name')},
        ),
    ]
