# Generated by Django 5.2.9 on 2026-01-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productcategory_unique_together_and_more'),
        ('b2b', '0001_initial'),  # B2BCategory doit exister avant d'ajouter la ForeignKey
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='b2b_category',
            field=models.ForeignKey(
                blank=True,
                help_text='Catégorie B2B (logique métier)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='products',
                to='b2b.b2bcategory',
            ),
        ),
    ]



