# Generated by Django 5.2.9 on 2026-01-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_add_b2b_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='market_type',
            field=models.CharField(
                choices=[
                    ('b2c', 'B2C - Vente au detail'),
                    ('b2b', 'B2B - Vente en gros'),
                    ('both', 'B2C et B2B'),
                ],
                default='b2c',
                help_text='Type de marche pour ce produit',
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['market_type', 'is_available'], name='product_market_avail_idx'),
        ),
    ]

