# Generated by Django 5.2.9 on 2026-01-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_add_market_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='market_type',
            field=models.CharField(choices=[('b2c', 'B2C - Vente au détail'), ('b2b', 'B2B - Vente en gros'), ('both', 'B2C et B2B')], default='b2c', help_text='Type de marché pour ce produit', max_length=10),
        ),
    ]
