# Generated by Django 5.2.9 on 2026-01-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_market_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Taux de commission en % pour les produits de cette catégorie', max_digits=5),
        ),
    ]
