# Generated by Django 5.2.9 on 2026-01-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_add_commission_rate_to_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Poids estimé si non renseigné (calculé automatiquement)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Poids du produit en kg', max_digits=8, null=True),
        ),
    ]
