# Generated by Django 5.2.8 on 2026-01-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_estimated_weight_kg_product_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longueur du produit en mètres', max_digits=6, null=True),
        ),
    ]
