# Generated by Django 5.2.17 on 2026-10-09 10:31

import stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_product_attributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=stores.models.default_commission_rate,
                help_text="Taux de commission en % pour les produits de cette catégorie",
                max_digits=5,
            ),
        ),
    ]
